/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlgoAcmItemDto
 */
export interface AlgoAcmItemDto {
    /**
     * 
     * @type {string}
     * @memberof AlgoAcmItemDto
     */
    requestId: string;
    /**
     * 
     * @type {string}
     * @memberof AlgoAcmItemDto
     */
    acm: string;
}

/**
 * Check if a given object implements the AlgoAcmItemDto interface.
 */
export function instanceOfAlgoAcmItemDto(value: object): boolean {
    if (!('requestId' in value)) return false;
    if (!('acm' in value)) return false;
    return true;
}

export function AlgoAcmItemDtoFromJSON(json: any): AlgoAcmItemDto {
    return AlgoAcmItemDtoFromJSONTyped(json, false);
}

export function AlgoAcmItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlgoAcmItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'],
        'acm': json['acm'],
    };
}

export function AlgoAcmItemDtoToJSON(value?: AlgoAcmItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'requestId': value['requestId'],
        'acm': value['acm'],
    };
}

