/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlgoAcmDto
 */
export interface AlgoAcmDto {
    /**
     * 
     * @type {string}
     * @memberof AlgoAcmDto
     */
    deyiInfo: string;
    /**
     * 
     * @type {string}
     * @memberof AlgoAcmDto
     */
    requestId: string;
}

/**
 * Check if a given object implements the AlgoAcmDto interface.
 */
export function instanceOfAlgoAcmDto(value: object): boolean {
    if (!('deyiInfo' in value)) return false;
    if (!('requestId' in value)) return false;
    return true;
}

export function AlgoAcmDtoFromJSON(json: any): AlgoAcmDto {
    return AlgoAcmDtoFromJSONTyped(json, false);
}

export function AlgoAcmDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlgoAcmDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deyiInfo': json['deyiInfo'],
        'requestId': json['requestId'],
    };
}

export function AlgoAcmDtoToJSON(value?: AlgoAcmDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'deyiInfo': value['deyiInfo'],
        'requestId': value['requestId'],
    };
}

