/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BasePropertyDto
 */
export interface BasePropertyDto {
  /**
   *
   * @type {string}
   * @memberof BasePropertyDto
   */
  value: string;
  /**
   *
   * @type {string}
   * @memberof BasePropertyDto
   */
  key: string;
  /**
   *
   * @type {boolean}
   * @memberof BasePropertyDto
   */
  customSortState?: boolean;
  /**
   *
   * @type {string}
   * @memberof BasePropertyDto
   */
  itemType?: string;
  /**
   *
   * @type {number}
   * @memberof BasePropertyDto
   */
  customSort?: number;
  /**
   *
   * @type {number}
   * @memberof BasePropertyDto
   */
  sort?: number;
  /**
   *
   * @type {string}
   * @memberof BasePropertyDto
   */
  primaryKey?: string;
  /**
   *
   * @type {number}
   * @memberof BasePropertyDto
   */
  defaultShow?: number;
  /**
   *
   * @type {number}
   * @memberof BasePropertyDto
   */
  supportCopy?: number;
  /**
   *
   * @type {string}
   * @memberof BasePropertyDto
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof BasePropertyDto
   */
  seriesId?: number;
}

/**
 * Check if a given object implements the BasePropertyDto interface.
 */
export function instanceOfBasePropertyDto(value: object): boolean {
  if (!("value" in value)) return false;
  if (!("key" in value)) return false;
  return true;
}

export function BasePropertyDtoFromJSON(json: any): BasePropertyDto {
  return BasePropertyDtoFromJSONTyped(json, false);
}

export function BasePropertyDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BasePropertyDto {
  if (json == null) {
    return json;
  }
  return {
    value: json["value"],
    key: json["key"],
    customSortState:
      json["customSortState"] == null ? undefined : json["customSortState"],
    itemType: json["itemType"] == null ? undefined : json["itemType"],
    customSort: json["customSort"] == null ? undefined : json["customSort"],
    sort: json["sort"] == null ? undefined : json["sort"],
    primaryKey: json["primaryKey"] == null ? undefined : json["primaryKey"],
    defaultShow: json["defaultShow"] == null ? undefined : json["defaultShow"],
    supportCopy: json["supportCopy"] == null ? undefined : json["supportCopy"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function BasePropertyDtoToJSON(value?: BasePropertyDto | null): any {
  if (value == null) {
    return value;
  }
  return {
    value: value["value"],
    key: value["key"],
    customSortState: value["customSortState"],
    itemType: value["itemType"],
    customSort: value["customSort"],
    sort: value["sort"],
    primaryKey: value["primaryKey"],
    defaultShow: value["defaultShow"],
    supportCopy: value["supportCopy"],
    name: value["name"],
  };
}
