/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BrandItemsModelDto
 */
export interface BrandItemsModelDto {
  /**
   *
   * @type {number}
   * @memberof BrandItemsModelDto
   */
  isShowBrand: number;
  /**
   *
   * @type {string}
   * @memberof BrandItemsModelDto
   */
  brandName: string;
  /**
   *
   * @type {string}
   * @memberof BrandItemsModelDto
   */
  linkUrl: string;
  /**
   *
   * @type {string}
   * @memberof BrandItemsModelDto
   */
  brandItems: string;
  /**
   *
   * @type {string}
   * @memberof BrandItemsModelDto
   */
  brandLogo: string;
  /**
   *
   * @type {string}
   * @memberof BrandItemsModelDto
   */
  brandId: number;
}

/**
 * Check if a given object implements the BrandItemsModelDto interface.
 */
export function instanceOfBrandItemsModelDto(value: object): boolean {
  if (!("isShowBrand" in value)) return false;
  if (!("brandName" in value)) return false;
  if (!("linkUrl" in value)) return false;
  if (!("brandItems" in value)) return false;
  if (!("brandLogo" in value)) return false;
  return true;
}

export function BrandItemsModelDtoFromJSON(json: any): BrandItemsModelDto {
  return BrandItemsModelDtoFromJSONTyped(json, false);
}

export function BrandItemsModelDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BrandItemsModelDto {
  if (json == null) {
    return json;
  }
  return {
    isShowBrand: json["isShowBrand"],
    brandName: json["brandName"],
    linkUrl: json["linkUrl"],
    brandItems: json["brandItems"],
    brandLogo: json["brandLogo"],
    brandId: json["brandId"],
  };
}

export function BrandItemsModelDtoToJSON(
  value?: BrandItemsModelDto | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    isShowBrand: value["isShowBrand"],
    brandName: value["brandName"],
    linkUrl: value["linkUrl"],
    brandItems: value["brandItems"],
    brandLogo: value["brandLogo"],
  };
}
