/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandDto } from './BrandDto';
import {
    BrandDtoFromJSON,
    BrandDtoFromJSONTyped,
    BrandDtoToJSON,
} from './BrandDto';
import type { MetaResponseDto } from './MetaResponseDto';
import {
    MetaResponseDtoFromJSON,
    MetaResponseDtoFromJSONTyped,
    MetaResponseDtoToJSON,
} from './MetaResponseDto';

/**
 * 
 * @export
 * @interface BrandsResponseWithPaginationDto
 */
export interface BrandsResponseWithPaginationDto {
    /**
     * 
     * @type {Array<BrandDto>}
     * @memberof BrandsResponseWithPaginationDto
     */
    data: Array<BrandDto>;
    /**
     * 
     * @type {MetaResponseDto}
     * @memberof BrandsResponseWithPaginationDto
     */
    meta: MetaResponseDto;
}

/**
 * Check if a given object implements the BrandsResponseWithPaginationDto interface.
 */
export function instanceOfBrandsResponseWithPaginationDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function BrandsResponseWithPaginationDtoFromJSON(json: any): BrandsResponseWithPaginationDto {
    return BrandsResponseWithPaginationDtoFromJSONTyped(json, false);
}

export function BrandsResponseWithPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandsResponseWithPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BrandDtoFromJSON)),
        'meta': MetaResponseDtoFromJSON(json['meta']),
    };
}

export function BrandsResponseWithPaginationDtoToJSON(value?: BrandsResponseWithPaginationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(BrandDtoToJSON)),
        'meta': MetaResponseDtoToJSON(value['meta']),
    };
}

