/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemListDto } from './ItemListDto';
import {
    ItemListDtoFromJSON,
    ItemListDtoFromJSONTyped,
    ItemListDtoToJSON,
} from './ItemListDto';

/**
 * 
 * @export
 * @interface BrandInfoDto
 */
export interface BrandInfoDto {
    /**
     * Метка сортировки
     * @type {string}
     * @memberof BrandInfoDto
     */
    sortLabel: string;
    /**
     * Список товаров бренда
     * @type {Array<ItemListDto>}
     * @memberof BrandInfoDto
     */
    itemList: Array<ItemListDto>;
    /**
     * Порядок сортировки
     * @type {number}
     * @memberof BrandInfoDto
     */
    sort: number;
}

/**
 * Check if a given object implements the BrandInfoDto interface.
 */
export function instanceOfBrandInfoDto(value: object): boolean {
    if (!('sortLabel' in value)) return false;
    if (!('itemList' in value)) return false;
    if (!('sort' in value)) return false;
    return true;
}

export function BrandInfoDtoFromJSON(json: any): BrandInfoDto {
    return BrandInfoDtoFromJSONTyped(json, false);
}

export function BrandInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sortLabel': json['sortLabel'],
        'itemList': ((json['itemList'] as Array<any>).map(ItemListDtoFromJSON)),
        'sort': json['sort'],
    };
}

export function BrandInfoDtoToJSON(value?: BrandInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sortLabel': value['sortLabel'],
        'itemList': ((value['itemList'] as Array<any>).map(ItemListDtoToJSON)),
        'sort': value['sort'],
    };
}

