/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandInfoDto } from './BrandInfoDto';
import {
    BrandInfoDtoFromJSON,
    BrandInfoDtoFromJSONTyped,
    BrandInfoDtoToJSON,
} from './BrandInfoDto';

/**
 * 
 * @export
 * @interface BrandListResponseDto
 */
export interface BrandListResponseDto {
    /**
     * Информация о брендах
     * @type {Array<BrandInfoDto>}
     * @memberof BrandListResponseDto
     */
    brandInfo: Array<BrandInfoDto>;
}

/**
 * Check if a given object implements the BrandListResponseDto interface.
 */
export function instanceOfBrandListResponseDto(value: object): boolean {
    if (!('brandInfo' in value)) return false;
    return true;
}

export function BrandListResponseDtoFromJSON(json: any): BrandListResponseDto {
    return BrandListResponseDtoFromJSONTyped(json, false);
}

export function BrandListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'brandInfo': ((json['brandInfo'] as Array<any>).map(BrandInfoDtoFromJSON)),
    };
}

export function BrandListResponseDtoToJSON(value?: BrandListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brandInfo': ((value['brandInfo'] as Array<any>).map(BrandInfoDtoToJSON)),
    };
}

