/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandDto
 */
export interface BrandDto {
    /**
     * Brand name (required if no ID)
     * @type {string}
     * @memberof BrandDto
     */
    name: string;
    /**
     * Brand ID if exists
     * @type {number}
     * @memberof BrandDto
     */
    id?: number;
    /**
     * Brand description
     * @type {string}
     * @memberof BrandDto
     */
    description?: string;
    /**
     * Brand logo URL
     * @type {string}
     * @memberof BrandDto
     */
    logoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    coverUrl?: string;
    /**
     * Количество продаваемых товаров бренда. Заполняется только при withCount=true.
     * @type {number}
     * @memberof BrandDto
     */
    productCount?: number;
}

/**
 * Check if a given object implements the BrandDto interface.
 */
export function instanceOfBrandDto(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function BrandDtoFromJSON(json: any): BrandDto {
    return BrandDtoFromJSONTyped(json, false);
}

export function BrandDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'productCount': json['productCount'] == null ? undefined : json['productCount'],
    };
}

export function BrandDtoToJSON(value?: BrandDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
        'coverUrl': value['coverUrl'],
        'productCount': value['productCount'],
    };
}

