/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomsInfoDto } from './CustomsInfoDto';
import {
    CustomsInfoDtoFromJSON,
    CustomsInfoDtoFromJSONTyped,
    CustomsInfoDtoToJSON,
} from './CustomsInfoDto';
import type { DetailDto } from './DetailDto';
import {
    DetailDtoFromJSON,
    DetailDtoFromJSONTyped,
    DetailDtoToJSON,
} from './DetailDto';
import type { SalePropertyDto } from './SalePropertyDto';
import {
    SalePropertyDtoFromJSON,
    SalePropertyDtoFromJSONTyped,
    SalePropertyDtoToJSON,
} from './SalePropertyDto';
import type { SkusDto } from './SkusDto';
import {
    SkusDtoFromJSON,
    SkusDtoFromJSONTyped,
    SkusDtoToJSON,
} from './SkusDto';

/**
 * 
 * @export
 * @interface BuyDialogModelDto
 */
export interface BuyDialogModelDto {
    /**
     * 
     * @type {object}
     * @memberof BuyDialogModelDto
     */
    saleImages: object;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    buyForTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    googleProductCategory: string;
    /**
     * 
     * @type {Array<SkusDto>}
     * @memberof BuyDialogModelDto
     */
    skus: Array<SkusDto>;
    /**
     * 
     * @type {CustomsInfoDto}
     * @memberof BuyDialogModelDto
     */
    customsInfo: CustomsInfoDto;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    estimateDefaultDesc: string;
    /**
     * 
     * @type {Array<SalePropertyDto>}
     * @memberof BuyDialogModelDto
     */
    saleProperties: Array<SalePropertyDto>;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    pdFrameLayoutAbValue: string;
    /**
     * 
     * @type {object}
     * @memberof BuyDialogModelDto
     */
    levelOneMinPriceSkus: object;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    skuSpeedTitle: string;
    /**
     * 
     * @type {number}
     * @memberof BuyDialogModelDto
     */
    contentCategory: number;
    /**
     * 
     * @type {boolean}
     * @memberof BuyDialogModelDto
     */
    sizeConversionAsianToUS: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BuyDialogModelDto
     */
    containGiftProp: boolean;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    noAvailableInvTitle: string;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    giftPropAbValue: string;
    /**
     * 
     * @type {string}
     * @memberof BuyDialogModelDto
     */
    floatingLayerTitle: string;
    /**
     * 
     * @type {object}
     * @memberof BuyDialogModelDto
     */
    skuMinPriceInfoDTO: object;
    /**
     * 
     * @type {DetailDto}
     * @memberof BuyDialogModelDto
     */
    detail: DetailDto;
    /**
     * 
     * @type {boolean}
     * @memberof BuyDialogModelDto
     */
    categoryUiOptimization: boolean;
}

/**
 * Check if a given object implements the BuyDialogModelDto interface.
 */
export function instanceOfBuyDialogModelDto(value: object): boolean {
    if (!('saleImages' in value)) return false;
    if (!('buyForTitle' in value)) return false;
    if (!('googleProductCategory' in value)) return false;
    if (!('skus' in value)) return false;
    if (!('customsInfo' in value)) return false;
    if (!('estimateDefaultDesc' in value)) return false;
    if (!('saleProperties' in value)) return false;
    if (!('pdFrameLayoutAbValue' in value)) return false;
    if (!('levelOneMinPriceSkus' in value)) return false;
    if (!('skuSpeedTitle' in value)) return false;
    if (!('contentCategory' in value)) return false;
    if (!('sizeConversionAsianToUS' in value)) return false;
    if (!('containGiftProp' in value)) return false;
    if (!('noAvailableInvTitle' in value)) return false;
    if (!('giftPropAbValue' in value)) return false;
    if (!('floatingLayerTitle' in value)) return false;
    if (!('skuMinPriceInfoDTO' in value)) return false;
    if (!('detail' in value)) return false;
    if (!('categoryUiOptimization' in value)) return false;
    return true;
}

export function BuyDialogModelDtoFromJSON(json: any): BuyDialogModelDto {
    return BuyDialogModelDtoFromJSONTyped(json, false);
}

export function BuyDialogModelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuyDialogModelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'saleImages': json['saleImages'],
        'buyForTitle': json['buyForTitle'],
        'googleProductCategory': json['googleProductCategory'],
        'skus': ((json['skus'] as Array<any>).map(SkusDtoFromJSON)),
        'customsInfo': CustomsInfoDtoFromJSON(json['customsInfo']),
        'estimateDefaultDesc': json['estimateDefaultDesc'],
        'saleProperties': ((json['saleProperties'] as Array<any>).map(SalePropertyDtoFromJSON)),
        'pdFrameLayoutAbValue': json['pdFrameLayoutAbValue'],
        'levelOneMinPriceSkus': json['levelOneMinPriceSkus'],
        'skuSpeedTitle': json['skuSpeedTitle'],
        'contentCategory': json['contentCategory'],
        'sizeConversionAsianToUS': json['sizeConversionAsianToUS'],
        'containGiftProp': json['containGiftProp'],
        'noAvailableInvTitle': json['noAvailableInvTitle'],
        'giftPropAbValue': json['giftPropAbValue'],
        'floatingLayerTitle': json['floatingLayerTitle'],
        'skuMinPriceInfoDTO': json['skuMinPriceInfoDTO'],
        'detail': DetailDtoFromJSON(json['detail']),
        'categoryUiOptimization': json['categoryUiOptimization'],
    };
}

export function BuyDialogModelDtoToJSON(value?: BuyDialogModelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'saleImages': value['saleImages'],
        'buyForTitle': value['buyForTitle'],
        'googleProductCategory': value['googleProductCategory'],
        'skus': ((value['skus'] as Array<any>).map(SkusDtoToJSON)),
        'customsInfo': CustomsInfoDtoToJSON(value['customsInfo']),
        'estimateDefaultDesc': value['estimateDefaultDesc'],
        'saleProperties': ((value['saleProperties'] as Array<any>).map(SalePropertyDtoToJSON)),
        'pdFrameLayoutAbValue': value['pdFrameLayoutAbValue'],
        'levelOneMinPriceSkus': value['levelOneMinPriceSkus'],
        'skuSpeedTitle': value['skuSpeedTitle'],
        'contentCategory': value['contentCategory'],
        'sizeConversionAsianToUS': value['sizeConversionAsianToUS'],
        'containGiftProp': value['containGiftProp'],
        'noAvailableInvTitle': value['noAvailableInvTitle'],
        'giftPropAbValue': value['giftPropAbValue'],
        'floatingLayerTitle': value['floatingLayerTitle'],
        'skuMinPriceInfoDTO': value['skuMinPriceInfoDTO'],
        'detail': DetailDtoToJSON(value['detail']),
        'categoryUiOptimization': value['categoryUiOptimization'],
    };
}

