/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTreeGroupDto } from './CategoryTreeGroupDto';
import {
    CategoryTreeGroupDtoFromJSON,
    CategoryTreeGroupDtoFromJSONTyped,
    CategoryTreeGroupDtoToJSON,
} from './CategoryTreeGroupDto';

/**
 * 
 * @export
 * @interface CategoryTreeNodeDto
 */
export interface CategoryTreeNodeDto {
    /**
     * id категории L1
     * @type {string}
     * @memberof CategoryTreeNodeDto
     */
    id: string;
    /**
     * Название категории
     * @type {string}
     * @memberof CategoryTreeNodeDto
     */
    name: string;
    /**
     * 
     * @type {Array<CategoryTreeGroupDto>}
     * @memberof CategoryTreeNodeDto
     */
    groups: Array<CategoryTreeGroupDto>;
}

/**
 * Check if a given object implements the CategoryTreeNodeDto interface.
 */
export function instanceOfCategoryTreeNodeDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('groups' in value)) return false;
    return true;
}

export function CategoryTreeNodeDtoFromJSON(json: any): CategoryTreeNodeDto {
    return CategoryTreeNodeDtoFromJSONTyped(json, false);
}

export function CategoryTreeNodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeNodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'groups': ((json['groups'] as Array<any>).map(CategoryTreeGroupDtoFromJSON)),
    };
}

export function CategoryTreeNodeDtoToJSON(value?: CategoryTreeNodeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'groups': ((value['groups'] as Array<any>).map(CategoryTreeGroupDtoToJSON)),
    };
}

