/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTreeItemDto } from './CategoryTreeItemDto';
import {
    CategoryTreeItemDtoFromJSON,
    CategoryTreeItemDtoFromJSONTyped,
    CategoryTreeItemDtoToJSON,
} from './CategoryTreeItemDto';

/**
 * 
 * @export
 * @interface CategoryTreeGroupDto
 */
export interface CategoryTreeGroupDto {
    /**
     * Заголовок группы
     * @type {string}
     * @memberof CategoryTreeGroupDto
     */
    title: string;
    /**
     * 
     * @type {Array<CategoryTreeItemDto>}
     * @memberof CategoryTreeGroupDto
     */
    items: Array<CategoryTreeItemDto>;
    /**
     * id виртуальной категории L2. Есть только там, где upstream группирует L3 по подразделам.
     * @type {string}
     * @memberof CategoryTreeGroupDto
     */
    level2Id?: string;
}

/**
 * Check if a given object implements the CategoryTreeGroupDto interface.
 */
export function instanceOfCategoryTreeGroupDto(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('items' in value)) return false;
    return true;
}

export function CategoryTreeGroupDtoFromJSON(json: any): CategoryTreeGroupDto {
    return CategoryTreeGroupDtoFromJSONTyped(json, false);
}

export function CategoryTreeGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'items': ((json['items'] as Array<any>).map(CategoryTreeItemDtoFromJSON)),
        'level2Id': json['level2Id'] == null ? undefined : json['level2Id'],
    };
}

export function CategoryTreeGroupDtoToJSON(value?: CategoryTreeGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'items': ((value['items'] as Array<any>).map(CategoryTreeItemDtoToJSON)),
        'level2Id': value['level2Id'],
    };
}

