/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {
    /**
     * Category name (required if no ID)
     * @type {string}
     * @memberof CategoryDto
     */
    name: string;
    /**
     * Category ID if exists
     * @type {number}
     * @memberof CategoryDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    logoUrl?: string;
    /**
     * Parent category ID
     * @type {number}
     * @memberof CategoryDto
     */
    parentId?: number;
    /**
     * Root category ID
     * @type {number}
     * @memberof CategoryDto
     */
    rootId?: number;
    /**
     * Количество товаров в категории с учётом подкатегорий. Заполняется только при withCount=true.
     * @type {number}
     * @memberof CategoryDto
     */
    productCount?: number;
}

/**
 * Check if a given object implements the CategoryDto interface.
 */
export function instanceOfCategoryDto(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CategoryDtoFromJSON(json: any): CategoryDto {
    return CategoryDtoFromJSONTyped(json, false);
}

export function CategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'rootId': json['rootId'] == null ? undefined : json['rootId'],
        'productCount': json['productCount'] == null ? undefined : json['productCount'],
    };
}

export function CategoryDtoToJSON(value?: CategoryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
        'logoUrl': value['logoUrl'],
        'parentId': value['parentId'],
        'rootId': value['rootId'],
        'productCount': value['productCount'],
    };
}

