/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryDto } from './CategoryDto';
import {
    CategoryDtoFromJSON,
    CategoryDtoFromJSONTyped,
    CategoryDtoToJSON,
} from './CategoryDto';
import type { MetaResponseDto } from './MetaResponseDto';
import {
    MetaResponseDtoFromJSON,
    MetaResponseDtoFromJSONTyped,
    MetaResponseDtoToJSON,
} from './MetaResponseDto';

/**
 * 
 * @export
 * @interface CategoriesResponseWithPaginationDto
 */
export interface CategoriesResponseWithPaginationDto {
    /**
     * 
     * @type {Array<CategoryDto>}
     * @memberof CategoriesResponseWithPaginationDto
     */
    data: Array<CategoryDto>;
    /**
     * 
     * @type {MetaResponseDto}
     * @memberof CategoriesResponseWithPaginationDto
     */
    meta: MetaResponseDto;
}

/**
 * Check if a given object implements the CategoriesResponseWithPaginationDto interface.
 */
export function instanceOfCategoriesResponseWithPaginationDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function CategoriesResponseWithPaginationDtoFromJSON(json: any): CategoriesResponseWithPaginationDto {
    return CategoriesResponseWithPaginationDtoFromJSONTyped(json, false);
}

export function CategoriesResponseWithPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesResponseWithPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CategoryDtoFromJSON)),
        'meta': MetaResponseDtoFromJSON(json['meta']),
    };
}

export function CategoriesResponseWithPaginationDtoToJSON(value?: CategoriesResponseWithPaginationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(CategoryDtoToJSON)),
        'meta': MetaResponseDtoToJSON(value['meta']),
    };
}

