/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacetDto } from './FacetDto';
import {
    FacetDtoFromJSON,
    FacetDtoFromJSONTyped,
    FacetDtoToJSON,
} from './FacetDto';

/**
 * 
 * @export
 * @interface CategoryFiltersResponseDto
 */
export interface CategoryFiltersResponseDto {
    /**
     * Доступные фильтры категории. Поле key каждого фасета совпадает с именем query-параметра фильтрации в /search и /search-by-category.
     * @type {Array<FacetDto>}
     * @memberof CategoryFiltersResponseDto
     */
    facets: Array<FacetDto>;
}

/**
 * Check if a given object implements the CategoryFiltersResponseDto interface.
 */
export function instanceOfCategoryFiltersResponseDto(value: object): boolean {
    if (!('facets' in value)) return false;
    return true;
}

export function CategoryFiltersResponseDtoFromJSON(json: any): CategoryFiltersResponseDto {
    return CategoryFiltersResponseDtoFromJSONTyped(json, false);
}

export function CategoryFiltersResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryFiltersResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'facets': ((json['facets'] as Array<any>).map(FacetDtoFromJSON)),
    };
}

export function CategoryFiltersResponseDtoToJSON(value?: CategoryFiltersResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'facets': ((value['facets'] as Array<any>).map(FacetDtoToJSON)),
    };
}

