/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryTreeItemDto
 */
export interface CategoryTreeItemDto {
    /**
     * id категории L3
     * @type {string}
     * @memberof CategoryTreeItemDto
     */
    id: string;
    /**
     * Название категории
     * @type {string}
     * @memberof CategoryTreeItemDto
     */
    name: string;
    /**
     * Иконка категории
     * @type {string}
     * @memberof CategoryTreeItemDto
     */
    imageUrl?: string;
    /**
     * Подпись с числом товаров, как её отдаёт upstream
     * @type {string}
     * @memberof CategoryTreeItemDto
     */
    productCountText?: string;
}

/**
 * Check if a given object implements the CategoryTreeItemDto interface.
 */
export function instanceOfCategoryTreeItemDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function CategoryTreeItemDtoFromJSON(json: any): CategoryTreeItemDto {
    return CategoryTreeItemDtoFromJSONTyped(json, false);
}

export function CategoryTreeItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'productCountText': json['productCountText'] == null ? undefined : json['productCountText'],
    };
}

export function CategoryTreeItemDtoToJSON(value?: CategoryTreeItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'productCountText': value['productCountText'],
    };
}

