/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryTreeNodeDto } from './CategoryTreeNodeDto';
import {
    CategoryTreeNodeDtoFromJSON,
    CategoryTreeNodeDtoFromJSONTyped,
    CategoryTreeNodeDtoToJSON,
} from './CategoryTreeNodeDto';

/**
 * 
 * @export
 * @interface CategoryTreeResponseDto
 */
export interface CategoryTreeResponseDto {
    /**
     * 
     * @type {Array<CategoryTreeNodeDto>}
     * @memberof CategoryTreeResponseDto
     */
    categories: Array<CategoryTreeNodeDto>;
}

/**
 * Check if a given object implements the CategoryTreeResponseDto interface.
 */
export function instanceOfCategoryTreeResponseDto(value: object): boolean {
    if (!('categories' in value)) return false;
    return true;
}

export function CategoryTreeResponseDtoFromJSON(json: any): CategoryTreeResponseDto {
    return CategoryTreeResponseDtoFromJSONTyped(json, false);
}

export function CategoryTreeResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryTreeResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(CategoryTreeNodeDtoFromJSON)),
    };
}

export function CategoryTreeResponseDtoToJSON(value?: CategoryTreeResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'categories': ((value['categories'] as Array<any>).map(CategoryTreeNodeDtoToJSON)),
    };
}

