/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShippingMethodDto } from './ShippingMethodDto';
import {
    ShippingMethodDtoFromJSON,
    ShippingMethodDtoFromJSONTyped,
    ShippingMethodDtoToJSON,
} from './ShippingMethodDto';

/**
 * 
 * @export
 * @interface ContentDto
 */
export interface ContentDto {
    /**
     * 
     * @type {string}
     * @memberof ContentDto
     */
    title: string;
    /**
     * 
     * @type {ShippingMethodDto}
     * @memberof ContentDto
     */
    contentInfo: ShippingMethodDto;
}

/**
 * Check if a given object implements the ContentDto interface.
 */
export function instanceOfContentDto(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('contentInfo' in value)) return false;
    return true;
}

export function ContentDtoFromJSON(json: any): ContentDto {
    return ContentDtoFromJSONTyped(json, false);
}

export function ContentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'contentInfo': ShippingMethodDtoFromJSON(json['contentInfo']),
    };
}

export function ContentDtoToJSON(value?: ContentDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'contentInfo': ShippingMethodDtoToJSON(value['contentInfo']),
    };
}

