/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponInfoDto
 */
export interface CouponInfoDto {
    /**
     * 
     * @type {string}
     * @memberof CouponInfoDto
     */
    backgroundColorHex: string;
    /**
     * 
     * @type {string}
     * @memberof CouponInfoDto
     */
    content: string;
}

/**
 * Check if a given object implements the CouponInfoDto interface.
 */
export function instanceOfCouponInfoDto(value: object): boolean {
    if (!('backgroundColorHex' in value)) return false;
    if (!('content' in value)) return false;
    return true;
}

export function CouponInfoDtoFromJSON(json: any): CouponInfoDto {
    return CouponInfoDtoFromJSONTyped(json, false);
}

export function CouponInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'backgroundColorHex': json['backgroundColorHex'],
        'content': json['content'],
    };
}

export function CouponInfoDtoToJSON(value?: CouponInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'backgroundColorHex': value['backgroundColorHex'],
        'content': value['content'],
    };
}

