/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductSelectionDto
 */
export interface CreateProductSelectionDto {
    /**
     * Название подборки (макс. 60 символов)
     * @type {string}
     * @memberof CreateProductSelectionDto
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateProductSelectionDto
     */
    productIds?: Array<number>;
}

/**
 * Check if a given object implements the CreateProductSelectionDto interface.
 */
export function instanceOfCreateProductSelectionDto(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CreateProductSelectionDtoFromJSON(json: any): CreateProductSelectionDto {
    return CreateProductSelectionDtoFromJSONTyped(json, false);
}

export function CreateProductSelectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductSelectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'productIds': json['productIds'] == null ? undefined : json['productIds'],
    };
}

export function CreateProductSelectionDtoToJSON(value?: CreateProductSelectionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'productIds': value['productIds'],
    };
}

