/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentDto } from './ContentDto';
import {
    ContentDtoFromJSON,
    ContentDtoFromJSONTyped,
    ContentDtoToJSON,
} from './ContentDto';
import type { IconDto } from './IconDto';
import {
    IconDtoFromJSON,
    IconDtoFromJSONTyped,
    IconDtoToJSON,
} from './IconDto';

/**
 * 
 * @export
 * @interface CustomsInfoDto
 */
export interface CustomsInfoDto {
    /**
     * 
     * @type {IconDto}
     * @memberof CustomsInfoDto
     */
    icon: IconDto;
    /**
     * 
     * @type {ContentDto}
     * @memberof CustomsInfoDto
     */
    content: ContentDto;
    /**
     * 
     * @type {string}
     * @memberof CustomsInfoDto
     */
    desc: string;
}

/**
 * Check if a given object implements the CustomsInfoDto interface.
 */
export function instanceOfCustomsInfoDto(value: object): boolean {
    if (!('icon' in value)) return false;
    if (!('content' in value)) return false;
    if (!('desc' in value)) return false;
    return true;
}

export function CustomsInfoDtoFromJSON(json: any): CustomsInfoDto {
    return CustomsInfoDtoFromJSONTyped(json, false);
}

export function CustomsInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomsInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'icon': IconDtoFromJSON(json['icon']),
        'content': ContentDtoFromJSON(json['content']),
        'desc': json['desc'],
    };
}

export function CustomsInfoDtoToJSON(value?: CustomsInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'icon': IconDtoToJSON(value['icon']),
        'content': ContentDtoToJSON(value['content']),
        'desc': value['desc'],
    };
}

