/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelListDto } from './LabelListDto';
import {
    LabelListDtoFromJSON,
    LabelListDtoFromJSONTyped,
    LabelListDtoToJSON,
} from './LabelListDto';

/**
 * 
 * @export
 * @interface DetailDto
 */
export interface DetailDto {
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    googleProductCategory: string;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    ageRange: string;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    fitId: number;
    /**
     * 
     * @type {boolean}
     * @memberof DetailDto
     */
    chineseMade: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    gender: string;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    frontCategoryId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof DetailDto
     */
    relationBrandIds: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DetailDto
     */
    seriesIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    frontCategoryName: string;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    areaName: string;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    level1CategoryId: number;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    brandName: string;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    sizeSystem: string;
    /**
     * 
     * @type {boolean}
     * @memberof DetailDto
     */
    bagWatchAccessory: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    logoUrl: string;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    contentCategory: number;
    /**
     * 
     * @type {Array<LabelListDto>}
     * @memberof DetailDto
     */
    labelList: Array<LabelListDto>;
    /**
     * 
     * @type {string}
     * @memberof DetailDto
     */
    createdBy: string;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    brandId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    buyStatus: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    spuId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    level2CategoryId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    globalSpuId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    categoryId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailDto
     */
    status: number;
}

/**
 * Check if a given object implements the DetailDto interface.
 */
export function instanceOfDetailDto(value: object): boolean {
    if (!('googleProductCategory' in value)) return false;
    if (!('ageRange' in value)) return false;
    if (!('fitId' in value)) return false;
    if (!('chineseMade' in value)) return false;
    if (!('gender' in value)) return false;
    if (!('language' in value)) return false;
    if (!('title' in value)) return false;
    if (!('frontCategoryId' in value)) return false;
    if (!('relationBrandIds' in value)) return false;
    if (!('seriesIds' in value)) return false;
    if (!('frontCategoryName' in value)) return false;
    if (!('areaName' in value)) return false;
    if (!('level1CategoryId' in value)) return false;
    if (!('brandName' in value)) return false;
    if (!('sizeSystem' in value)) return false;
    if (!('bagWatchAccessory' in value)) return false;
    if (!('logoUrl' in value)) return false;
    if (!('contentCategory' in value)) return false;
    if (!('labelList' in value)) return false;
    if (!('createdBy' in value)) return false;
    if (!('brandId' in value)) return false;
    if (!('buyStatus' in value)) return false;
    if (!('spuId' in value)) return false;
    if (!('level2CategoryId' in value)) return false;
    if (!('globalSpuId' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function DetailDtoFromJSON(json: any): DetailDto {
    return DetailDtoFromJSONTyped(json, false);
}

export function DetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'googleProductCategory': json['googleProductCategory'],
        'ageRange': json['ageRange'],
        'fitId': json['fitId'],
        'chineseMade': json['chineseMade'],
        'gender': json['gender'],
        'language': json['language'],
        'title': json['title'],
        'frontCategoryId': json['frontCategoryId'],
        'relationBrandIds': json['relationBrandIds'],
        'seriesIds': json['seriesIds'],
        'frontCategoryName': json['frontCategoryName'],
        'areaName': json['areaName'],
        'level1CategoryId': json['level1CategoryId'],
        'brandName': json['brandName'],
        'sizeSystem': json['sizeSystem'],
        'bagWatchAccessory': json['bagWatchAccessory'],
        'logoUrl': json['logoUrl'],
        'contentCategory': json['contentCategory'],
        'labelList': ((json['labelList'] as Array<any>).map(LabelListDtoFromJSON)),
        'createdBy': json['createdBy'],
        'brandId': json['brandId'],
        'buyStatus': json['buyStatus'],
        'spuId': json['spuId'],
        'level2CategoryId': json['level2CategoryId'],
        'globalSpuId': json['globalSpuId'],
        'categoryId': json['categoryId'],
        'status': json['status'],
    };
}

export function DetailDtoToJSON(value?: DetailDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'googleProductCategory': value['googleProductCategory'],
        'ageRange': value['ageRange'],
        'fitId': value['fitId'],
        'chineseMade': value['chineseMade'],
        'gender': value['gender'],
        'language': value['language'],
        'title': value['title'],
        'frontCategoryId': value['frontCategoryId'],
        'relationBrandIds': value['relationBrandIds'],
        'seriesIds': value['seriesIds'],
        'frontCategoryName': value['frontCategoryName'],
        'areaName': value['areaName'],
        'level1CategoryId': value['level1CategoryId'],
        'brandName': value['brandName'],
        'sizeSystem': value['sizeSystem'],
        'bagWatchAccessory': value['bagWatchAccessory'],
        'logoUrl': value['logoUrl'],
        'contentCategory': value['contentCategory'],
        'labelList': ((value['labelList'] as Array<any>).map(LabelListDtoToJSON)),
        'createdBy': value['createdBy'],
        'brandId': value['brandId'],
        'buyStatus': value['buyStatus'],
        'spuId': value['spuId'],
        'level2CategoryId': value['level2CategoryId'],
        'globalSpuId': value['globalSpuId'],
        'categoryId': value['categoryId'],
        'status': value['status'],
    };
}

