/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacetItemDto } from './FacetItemDto';
import {
    FacetItemDtoFromJSON,
    FacetItemDtoFromJSONTyped,
    FacetItemDtoToJSON,
} from './FacetItemDto';
import type { NestedFacetDto } from './NestedFacetDto';
import {
    NestedFacetDtoFromJSON,
    NestedFacetDtoFromJSONTyped,
    NestedFacetDtoToJSON,
} from './NestedFacetDto';

/**
 * 
 * @export
 * @interface FacetDto
 */
export interface FacetDto {
    module: string;
    /**
     * 
     * @type {string}
     * @memberof FacetDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof FacetDto
     */
    defaultShow: boolean;
    /**
     * 
     * @type {number}
     * @memberof FacetDto
     */
    type: number;
    /**
     * 
     * @type {Array<FacetItemDto>}
     * @memberof FacetDto
     */
    items: Array<FacetItemDto>;
    /**
     * 
     * @type {boolean}
     * @memberof FacetDto
     */
    nested: boolean;
    /**
     * 
     * @type {string}
     * @memberof FacetDto
     */
    key: string;
    /**
     * 
     * @type {boolean}
     * @memberof FacetDto
     */
    unfold: boolean;
    /**
     * 
     * @type {Array<NestedFacetDto>}
     * @memberof FacetDto
     */
    nestedFacets?: Array<NestedFacetDto>;
}

/**
 * Check if a given object implements the FacetDto interface.
 */
export function instanceOfFacetDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('defaultShow' in value)) return false;
    if (!('type' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nested' in value)) return false;
    if (!('key' in value)) return false;
    if (!('unfold' in value)) return false;
    return true;
}

export function FacetDtoFromJSON(json: any): FacetDto {
    return FacetDtoFromJSONTyped(json, false);
}

export function FacetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'defaultShow': json['defaultShow'],
        'type': json['type'],
        'items': ((json['items'] as Array<any>).map(FacetItemDtoFromJSON)),
        'nested': json['nested'],
        'key': json['key'],
        'unfold': json['unfold'],
        'nestedFacets': json['nestedFacets'] == null ? undefined : ((json['nestedFacets'] as Array<any>).map(NestedFacetDtoFromJSON)),
    };
}

export function FacetDtoToJSON(value?: FacetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'defaultShow': value['defaultShow'],
        'type': value['type'],
        'items': ((value['items'] as Array<any>).map(FacetItemDtoToJSON)),
        'nested': value['nested'],
        'key': value['key'],
        'unfold': value['unfold'],
        'nestedFacets': value['nestedFacets'] == null ? undefined : ((value['nestedFacets'] as Array<any>).map(NestedFacetDtoToJSON)),
    };
}

