/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacetItemDto
 */
export interface FacetItemDto {
    /**
     * 
     * @type {string}
     * @memberof FacetItemDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FacetItemDto
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof FacetItemDto
     */
    value: string;
}

/**
 * Check if a given object implements the FacetItemDto interface.
 */
export function instanceOfFacetItemDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('count' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function FacetItemDtoFromJSON(json: any): FacetItemDto {
    return FacetItemDtoFromJSONTyped(json, false);
}

export function FacetItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'value': json['value'],
    };
}

export function FacetItemDtoToJSON(value?: FacetItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'count': value['count'],
        'value': value['value'],
    };
}

