/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IconDto
 */
export interface IconDto {
    /**
     * 
     * @type {string}
     * @memberof IconDto
     */
    icon: string;
    /**
     * 
     * @type {number}
     * @memberof IconDto
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof IconDto
     */
    height: number;
}

/**
 * Check if a given object implements the IconDto interface.
 */
export function instanceOfIconDto(value: object): boolean {
    if (!('icon' in value)) return false;
    if (!('width' in value)) return false;
    if (!('height' in value)) return false;
    return true;
}

export function IconDtoFromJSON(json: any): IconDto {
    return IconDtoFromJSONTyped(json, false);
}

export function IconDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IconDto {
    if (json == null) {
        return json;
    }
    return {
        
        'icon': json['icon'],
        'width': json['width'],
        'height': json['height'],
    };
}

export function IconDtoToJSON(value?: IconDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'icon': value['icon'],
        'width': value['width'],
        'height': value['height'],
    };
}

