/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageDto
 */
export interface ImageDto {
    /**
     * URL изображения
     * @type {string}
     * @memberof ImageDto
     */
    image: string;
    /**
     * Порядковый номер изображения
     * @type {number}
     * @memberof ImageDto
     */
    order: number;
}

/**
 * Check if a given object implements the ImageDto interface.
 */
export function instanceOfImageDto(value: object): boolean {
    if (!('image' in value)) return false;
    if (!('order' in value)) return false;
    return true;
}

export function ImageDtoFromJSON(json: any): ImageDto {
    return ImageDtoFromJSONTyped(json, false);
}

export function ImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'order': json['order'],
    };
}

export function ImageDtoToJSON(value?: ImageDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image': value['image'],
        'order': value['order'],
    };
}

