/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemListDto
 */
export interface ItemListDto {
    /**
     * ID бренда
     * @type {number}
     * @memberof ItemListDto
     */
    brandId: number;
    /**
     * Название бренда
     * @type {string}
     * @memberof ItemListDto
     */
    name: string;
    /**
     * URL иконки бренда
     * @type {string}
     * @memberof ItemListDto
     */
    icon: string;
}

/**
 * Check if a given object implements the ItemListDto interface.
 */
export function instanceOfItemListDto(value: object): boolean {
    if (!('brandId' in value)) return false;
    if (!('name' in value)) return false;
    if (!('icon' in value)) return false;
    return true;
}

export function ItemListDtoFromJSON(json: any): ItemListDto {
    return ItemListDtoFromJSONTyped(json, false);
}

export function ItemListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'brandId': json['brandId'],
        'name': json['name'],
        'icon': json['icon'],
    };
}

export function ItemListDtoToJSON(value?: ItemListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brandId': value['brandId'],
        'name': value['name'],
        'icon': value['icon'],
    };
}

