/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelListDto
 */
export interface LabelListDto {
    /**
     * 
     * @type {number}
     * @memberof LabelListDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LabelListDto
     */
    labelName: string;
}

/**
 * Check if a given object implements the LabelListDto interface.
 */
export function instanceOfLabelListDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('labelName' in value)) return false;
    return true;
}

export function LabelListDtoFromJSON(json: any): LabelListDto {
    return LabelListDtoFromJSONTyped(json, false);
}

export function LabelListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'labelName': json['labelName'],
    };
}

export function LabelListDtoToJSON(value?: LabelListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'labelName': value['labelName'],
    };
}

