/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelModelDto
 */
export interface LabelModelDto {
    /**
     * 
     * @type {number}
     * @memberof LabelModelDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LabelModelDto
     */
    labelName: string;
}

/**
 * Check if a given object implements the LabelModelDto interface.
 */
export function instanceOfLabelModelDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('labelName' in value)) return false;
    return true;
}

export function LabelModelDtoFromJSON(json: any): LabelModelDto {
    return LabelModelDtoFromJSONTyped(json, false);
}

export function LabelModelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelModelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'labelName': json['labelName'],
    };
}

export function LabelModelDtoToJSON(value?: LabelModelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'labelName': value['labelName'],
    };
}

