/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaResponse
 */
export interface MetaResponse {
    /**
     * 
     * @type {number}
     * @memberof MetaResponse
     */
    limit: number;
    /**
     * 
     * @type {boolean}
     * @memberof MetaResponse
     */
    hasNext: boolean;
    /**
     * 
     * @type {string}
     * @memberof MetaResponse
     */
    cursor?: string;
}

/**
 * Check if a given object implements the MetaResponse interface.
 */
export function instanceOfMetaResponse(value: object): boolean {
    if (!('limit' in value)) return false;
    if (!('hasNext' in value)) return false;
    return true;
}

export function MetaResponseFromJSON(json: any): MetaResponse {
    return MetaResponseFromJSONTyped(json, false);
}

export function MetaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'hasNext': json['hasNext'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
    };
}

export function MetaResponseToJSON(value?: MetaResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'limit': value['limit'],
        'hasNext': value['hasNext'],
        'cursor': value['cursor'],
    };
}

