/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaResponseDto
 */
export interface MetaResponseDto {
    /**
     * 
     * @type {number}
     * @memberof MetaResponseDto
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof MetaResponseDto
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaResponseDto
     */
    cursor?: number;
}

/**
 * Check if a given object implements the MetaResponseDto interface.
 */
export function instanceOfMetaResponseDto(value: object): boolean {
    if (!('total' in value)) return false;
    return true;
}

export function MetaResponseDtoFromJSON(json: any): MetaResponseDto {
    return MetaResponseDtoFromJSONTyped(json, false);
}

export function MetaResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
    };
}

export function MetaResponseDtoToJSON(value?: MetaResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'cursor': value['cursor'],
    };
}

