/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MoneyDto } from './MoneyDto';
import {
    MoneyDtoFromJSON,
    MoneyDtoFromJSONTyped,
    MoneyDtoToJSON,
} from './MoneyDto';

/**
 * 
 * @export
 * @interface MinSpuPriceDto
 */
export interface MinSpuPriceDto {
    /**
     * 
     * @type {string}
     * @memberof MinSpuPriceDto
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof MinSpuPriceDto
     */
    localizedDisplayText: string;
    /**
     * 
     * @type {MoneyDto}
     * @memberof MinSpuPriceDto
     */
    money: MoneyDto;
    /**
     * 
     * @type {string}
     * @memberof MinSpuPriceDto
     */
    amountText: string;
    /**
     * 
     * @type {string}
     * @memberof MinSpuPriceDto
     */
    sign: string;
    /**
     * 
     * @type {string}
     * @memberof MinSpuPriceDto
     */
    absText: string;
}

/**
 * Check if a given object implements the MinSpuPriceDto interface.
 */
export function instanceOfMinSpuPriceDto(value: object): boolean {
    if (!('symbol' in value)) return false;
    if (!('localizedDisplayText' in value)) return false;
    if (!('money' in value)) return false;
    if (!('amountText' in value)) return false;
    if (!('sign' in value)) return false;
    if (!('absText' in value)) return false;
    return true;
}

export function MinSpuPriceDtoFromJSON(json: any): MinSpuPriceDto {
    return MinSpuPriceDtoFromJSONTyped(json, false);
}

export function MinSpuPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinSpuPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'localizedDisplayText': json['localizedDisplayText'],
        'money': MoneyDtoFromJSON(json['money']),
        'amountText': json['amountText'],
        'sign': json['sign'],
        'absText': json['absText'],
    };
}

export function MinSpuPriceDtoToJSON(value?: MinSpuPriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'symbol': value['symbol'],
        'localizedDisplayText': value['localizedDisplayText'],
        'money': MoneyDtoToJSON(value['money']),
        'amountText': value['amountText'],
        'sign': value['sign'],
        'absText': value['absText'],
    };
}

