/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaResponseDto } from './MetaResponseDto';
import {
    MetaResponseDtoFromJSON,
    MetaResponseDtoFromJSONTyped,
    MetaResponseDtoToJSON,
} from './MetaResponseDto';
import type { ModelDto } from './ModelDto';
import {
    ModelDtoFromJSON,
    ModelDtoFromJSONTyped,
    ModelDtoToJSON,
} from './ModelDto';

/**
 * 
 * @export
 * @interface ModelsResponseWithPaginationDto
 */
export interface ModelsResponseWithPaginationDto {
    /**
     * 
     * @type {Array<ModelDto>}
     * @memberof ModelsResponseWithPaginationDto
     */
    data: Array<ModelDto>;
    /**
     * 
     * @type {MetaResponseDto}
     * @memberof ModelsResponseWithPaginationDto
     */
    meta: MetaResponseDto;
}

/**
 * Check if a given object implements the ModelsResponseWithPaginationDto interface.
 */
export function instanceOfModelsResponseWithPaginationDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ModelsResponseWithPaginationDtoFromJSON(json: any): ModelsResponseWithPaginationDto {
    return ModelsResponseWithPaginationDtoFromJSONTyped(json, false);
}

export function ModelsResponseWithPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponseWithPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ModelDtoFromJSON)),
        'meta': MetaResponseDtoFromJSON(json['meta']),
    };
}

export function ModelsResponseWithPaginationDtoToJSON(value?: ModelsResponseWithPaginationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ModelDtoToJSON)),
        'meta': MetaResponseDtoToJSON(value['meta']),
    };
}

