/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelDto
 */
export interface ModelDto {
    /**
     * Model name (required if no ID)
     * @type {string}
     * @memberof ModelDto
     */
    name: string;
    /**
     * Brand ID
     * @type {number}
     * @memberof ModelDto
     */
    brandId: number;
    /**
     * Model ID if exists
     * @type {number}
     * @memberof ModelDto
     */
    id?: number;
    /**
     * Model logo URL
     * @type {string}
     * @memberof ModelDto
     */
    logoUrl?: string;
}

/**
 * Check if a given object implements the ModelDto interface.
 */
export function instanceOfModelDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('brandId' in value)) return false;
    return true;
}

export function ModelDtoFromJSON(json: any): ModelDto {
    return ModelDtoFromJSONTyped(json, false);
}

export function ModelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'brandId': json['brandId'],
        'id': json['id'] == null ? undefined : json['id'],
        'logoUrl': json['logoUrl'] == null ? undefined : json['logoUrl'],
    };
}

export function ModelDtoToJSON(value?: ModelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'brandId': value['brandId'],
        'id': value['id'],
        'logoUrl': value['logoUrl'],
    };
}

