/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifySelectionDto
 */
export interface ModifySelectionDto {
    /**
     * 
     * @type {Array<number>}
     * @memberof ModifySelectionDto
     */
    productIds: Array<number>;
}

/**
 * Check if a given object implements the ModifySelectionDto interface.
 */
export function instanceOfModifySelectionDto(value: object): boolean {
    if (!('productIds' in value)) return false;
    return true;
}

export function ModifySelectionDtoFromJSON(json: any): ModifySelectionDto {
    return ModifySelectionDtoFromJSONTyped(json, false);
}

export function ModifySelectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifySelectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productIds': json['productIds'],
    };
}

export function ModifySelectionDtoToJSON(value?: ModifySelectionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productIds': value['productIds'],
    };
}

