/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MoneyDto
 */
export interface MoneyDto {
    /**
     * 
     * @type {string}
     * @memberof MoneyDto
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof MoneyDto
     */
    minUnitVal: number;
    /**
     * 
     * @type {string}
     * @memberof MoneyDto
     */
    currency: string;
}

/**
 * Check if a given object implements the MoneyDto interface.
 */
export function instanceOfMoneyDto(value: object): boolean {
    if (!('amount' in value)) return false;
    if (!('minUnitVal' in value)) return false;
    if (!('currency' in value)) return false;
    return true;
}

export function MoneyDtoFromJSON(json: any): MoneyDto {
    return MoneyDtoFromJSONTyped(json, false);
}

export function MoneyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'minUnitVal': json['minUnitVal'],
        'currency': json['currency'],
    };
}

export function MoneyDtoToJSON(value?: MoneyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'minUnitVal': value['minUnitVal'],
        'currency': value['currency'],
    };
}

