/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacetItemDto } from './FacetItemDto';
import {
    FacetItemDtoFromJSON,
    FacetItemDtoFromJSONTyped,
    FacetItemDtoToJSON,
} from './FacetItemDto';

/**
 * 
 * @export
 * @interface NestedFacetDto
 */
export interface NestedFacetDto {
    /**
     * 
     * @type {string}
     * @memberof NestedFacetDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof NestedFacetDto
     */
    defaultShow: boolean;
    /**
     * 
     * @type {number}
     * @memberof NestedFacetDto
     */
    type: number;
    /**
     * 
     * @type {Array<FacetItemDto>}
     * @memberof NestedFacetDto
     */
    items: Array<FacetItemDto>;
    /**
     * 
     * @type {boolean}
     * @memberof NestedFacetDto
     */
    nested: boolean;
    /**
     * 
     * @type {string}
     * @memberof NestedFacetDto
     */
    key: string;
    /**
     * 
     * @type {boolean}
     * @memberof NestedFacetDto
     */
    unfold: boolean;
}

/**
 * Check if a given object implements the NestedFacetDto interface.
 */
export function instanceOfNestedFacetDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('defaultShow' in value)) return false;
    if (!('type' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nested' in value)) return false;
    if (!('key' in value)) return false;
    if (!('unfold' in value)) return false;
    return true;
}

export function NestedFacetDtoFromJSON(json: any): NestedFacetDto {
    return NestedFacetDtoFromJSONTyped(json, false);
}

export function NestedFacetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NestedFacetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'defaultShow': json['defaultShow'],
        'type': json['type'],
        'items': ((json['items'] as Array<any>).map(FacetItemDtoFromJSON)),
        'nested': json['nested'],
        'key': json['key'],
        'unfold': json['unfold'],
    };
}

export function NestedFacetDtoToJSON(value?: NestedFacetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'defaultShow': value['defaultShow'],
        'type': value['type'],
        'items': ((value['items'] as Array<any>).map(FacetItemDtoToJSON)),
        'nested': value['nested'],
        'key': value['key'],
        'unfold': value['unfold'],
    };
}

