/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MoneyDto } from './MoneyDto';
import {
    MoneyDtoFromJSON,
    MoneyDtoFromJSONTyped,
    MoneyDtoToJSON,
} from './MoneyDto';

/**
 * 
 * @export
 * @interface PriceDto
 */
export interface PriceDto {
    /**
     * 
     * @type {MoneyDto}
     * @memberof PriceDto
     */
    money: MoneyDto;
    /**
     * 
     * @type {string}
     * @memberof PriceDto
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceDto
     */
    amountText?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceDto
     */
    sign?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceDto
     */
    absText?: string;
}

/**
 * Check if a given object implements the PriceDto interface.
 */
export function instanceOfPriceDto(value: object): boolean {
    if (!('money' in value)) return false;
    return true;
}

export function PriceDtoFromJSON(json: any): PriceDto {
    return PriceDtoFromJSONTyped(json, false);
}

export function PriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'money': MoneyDtoFromJSON(json['money']),
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'amountText': json['amountText'] == null ? undefined : json['amountText'],
        'sign': json['sign'] == null ? undefined : json['sign'],
        'absText': json['absText'] == null ? undefined : json['absText'],
    };
}

export function PriceDtoToJSON(value?: PriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'money': MoneyDtoToJSON(value['money']),
        'symbol': value['symbol'],
        'amountText': value['amountText'],
        'sign': value['sign'],
        'absText': value['absText'],
    };
}

