/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceDto
 */
export interface PriceDto {
    /**
     * Minimum price
     * @type {number}
     * @memberof PriceDto
     */
    minPrice: number;
    /**
     * Maximum price
     * @type {number}
     * @memberof PriceDto
     */
    maxPrice: number;
    /**
     * Currency
     * @type {string}
     * @memberof PriceDto
     */
    currency: PriceDtoCurrencyEnum;
}


/**
 * @export
 */
export const PriceDtoCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type PriceDtoCurrencyEnum = typeof PriceDtoCurrencyEnum[keyof typeof PriceDtoCurrencyEnum];


/**
 * Check if a given object implements the PriceDto interface.
 */
export function instanceOfPriceDto(value: object): boolean {
    if (!('minPrice' in value)) return false;
    if (!('maxPrice' in value)) return false;
    if (!('currency' in value)) return false;
    return true;
}

export function PriceDtoFromJSON(json: any): PriceDto {
    return PriceDtoFromJSONTyped(json, false);
}

export function PriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
        'currency': json['currency'],
    };
}

export function PriceDtoToJSON(value?: PriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'minPrice': value['minPrice'],
        'maxPrice': value['maxPrice'],
        'currency': value['currency'],
    };
}

