/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductByExternalIdResponseDto
 */
export interface ProductByExternalIdResponseDto {
    /**
     * Internal Product ID
     * @type {number}
     * @memberof ProductByExternalIdResponseDto
     */
    productId: number;
}

/**
 * Check if a given object implements the ProductByExternalIdResponseDto interface.
 */
export function instanceOfProductByExternalIdResponseDto(value: object): boolean {
    if (!('productId' in value)) return false;
    return true;
}

export function ProductByExternalIdResponseDtoFromJSON(json: any): ProductByExternalIdResponseDto {
    return ProductByExternalIdResponseDtoFromJSONTyped(json, false);
}

export function ProductByExternalIdResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductByExternalIdResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
    };
}

export function ProductByExternalIdResponseDtoToJSON(value?: ProductByExternalIdResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productId': value['productId'],
    };
}

