/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandDto } from './BrandDto';
import {
    BrandDtoFromJSON,
    BrandDtoFromJSONTyped,
    BrandDtoToJSON,
} from './BrandDto';
import type { CategoryDto } from './CategoryDto';
import {
    CategoryDtoFromJSON,
    CategoryDtoFromJSONTyped,
    CategoryDtoToJSON,
} from './CategoryDto';
import type { ImageDto } from './ImageDto';
import {
    ImageDtoFromJSON,
    ImageDtoFromJSONTyped,
    ImageDtoToJSON,
} from './ImageDto';
import type { ModelDto } from './ModelDto';
import {
    ModelDtoFromJSON,
    ModelDtoFromJSONTyped,
    ModelDtoToJSON,
} from './ModelDto';
import type { ProductSourceDto } from './ProductSourceDto';
import {
    ProductSourceDtoFromJSON,
    ProductSourceDtoFromJSONTyped,
    ProductSourceDtoToJSON,
} from './ProductSourceDto';
import type { PropertyDto } from './PropertyDto';
import {
    PropertyDtoFromJSON,
    PropertyDtoFromJSONTyped,
    PropertyDtoToJSON,
} from './PropertyDto';

/**
 * 
 * @export
 * @interface ProductDetailResponseDto
 */
export interface ProductDetailResponseDto {
    /**
     * ID продукта
     * @type {number}
     * @memberof ProductDetailResponseDto
     */
    id: number;
    /**
     * Артикул продукта
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    article: string;
    /**
     * Основное изображение
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    logoUrl: string;
    /**
     * Пол
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    gender: ProductDetailResponseDtoGenderEnum;
    /**
     * Количество добавлений в избранное
     * @type {number}
     * @memberof ProductDetailResponseDto
     */
    favoriteCount: number;
    /**
     * Количество продаж
     * @type {number}
     * @memberof ProductDetailResponseDto
     */
    soldCount: number;
    /**
     * Популярность 0–100
     * @type {number}
     * @memberof ProductDetailResponseDto
     */
    popularityScore: number;
    /**
     * Source
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    mainSource: ProductDetailResponseDtoMainSourceEnum;
    /**
     * Бренд продукта
     * @type {BrandDto}
     * @memberof ProductDetailResponseDto
     */
    brand: BrandDto;
    /**
     * Категория продукта
     * @type {CategoryDto}
     * @memberof ProductDetailResponseDto
     */
    category: CategoryDto;
    /**
     * Свойства продукта
     * @type {Array<PropertyDto>}
     * @memberof ProductDetailResponseDto
     */
    properties: Array<PropertyDto>;
    /**
     * Изображения продукта
     * @type {Array<ImageDto>}
     * @memberof ProductDetailResponseDto
     */
    productImages: Array<ImageDto>;
    /**
     * Product sources
     * @type {Array<ProductSourceDto>}
     * @memberof ProductDetailResponseDto
     */
    productSources: Array<ProductSourceDto>;
    /**
     * Название продукта
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    title?: string;
    /**
     * Описание
     * @type {string}
     * @memberof ProductDetailResponseDto
     */
    description?: string;
    /**
     * Модель продукта
     * @type {ModelDto}
     * @memberof ProductDetailResponseDto
     */
    model?: ModelDto;
}


/**
 * @export
 */
export const ProductDetailResponseDtoGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductDetailResponseDtoGenderEnum = typeof ProductDetailResponseDtoGenderEnum[keyof typeof ProductDetailResponseDtoGenderEnum];

/**
 * @export
 */
export const ProductDetailResponseDtoMainSourceEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductDetailResponseDtoMainSourceEnum = typeof ProductDetailResponseDtoMainSourceEnum[keyof typeof ProductDetailResponseDtoMainSourceEnum];


/**
 * Check if a given object implements the ProductDetailResponseDto interface.
 */
export function instanceOfProductDetailResponseDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('article' in value)) return false;
    if (!('logoUrl' in value)) return false;
    if (!('gender' in value)) return false;
    if (!('favoriteCount' in value)) return false;
    if (!('soldCount' in value)) return false;
    if (!('popularityScore' in value)) return false;
    if (!('mainSource' in value)) return false;
    if (!('brand' in value)) return false;
    if (!('category' in value)) return false;
    if (!('properties' in value)) return false;
    if (!('productImages' in value)) return false;
    if (!('productSources' in value)) return false;
    return true;
}

export function ProductDetailResponseDtoFromJSON(json: any): ProductDetailResponseDto {
    return ProductDetailResponseDtoFromJSONTyped(json, false);
}

export function ProductDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'article': json['article'],
        'logoUrl': json['logoUrl'],
        'gender': json['gender'],
        'favoriteCount': json['favoriteCount'],
        'soldCount': json['soldCount'],
        'popularityScore': json['popularityScore'],
        'mainSource': json['mainSource'],
        'brand': BrandDtoFromJSON(json['brand']),
        'category': CategoryDtoFromJSON(json['category']),
        'properties': ((json['properties'] as Array<any>).map(PropertyDtoFromJSON)),
        'productImages': ((json['productImages'] as Array<any>).map(ImageDtoFromJSON)),
        'productSources': ((json['productSources'] as Array<any>).map(ProductSourceDtoFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'model': json['model'] == null ? undefined : ModelDtoFromJSON(json['model']),
    };
}

export function ProductDetailResponseDtoToJSON(value?: ProductDetailResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'article': value['article'],
        'logoUrl': value['logoUrl'],
        'gender': value['gender'],
        'favoriteCount': value['favoriteCount'],
        'soldCount': value['soldCount'],
        'popularityScore': value['popularityScore'],
        'mainSource': value['mainSource'],
        'brand': BrandDtoToJSON(value['brand']),
        'category': CategoryDtoToJSON(value['category']),
        'properties': ((value['properties'] as Array<any>).map(PropertyDtoToJSON)),
        'productImages': ((value['productImages'] as Array<any>).map(ImageDtoToJSON)),
        'productSources': ((value['productSources'] as Array<any>).map(ProductSourceDtoToJSON)),
        'title': value['title'],
        'description': value['description'],
        'model': ModelDtoToJSON(value['model']),
    };
}

