/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceDto } from './PriceDto';
import {
    PriceDtoFromJSON,
    PriceDtoFromJSONTyped,
    PriceDtoToJSON,
} from './PriceDto';

/**
 * 
 * @export
 * @interface ProductSourceDto
 */
export interface ProductSourceDto {
    /**
     * Product source title
     * @type {string}
     * @memberof ProductSourceDto
     */
    title: string;
    /**
     * Source
     * @type {string}
     * @memberof ProductSourceDto
     */
    source: ProductSourceDtoSourceEnum;
    /**
     * External ID
     * @type {string}
     * @memberof ProductSourceDto
     */
    externalId?: string;
    /**
     * Price information
     * @type {PriceDto}
     * @memberof ProductSourceDto
     */
    price?: PriceDto;
}


/**
 * @export
 */
export const ProductSourceDtoSourceEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductSourceDtoSourceEnum = typeof ProductSourceDtoSourceEnum[keyof typeof ProductSourceDtoSourceEnum];


/**
 * Check if a given object implements the ProductSourceDto interface.
 */
export function instanceOfProductSourceDto(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('source' in value)) return false;
    return true;
}

export function ProductSourceDtoFromJSON(json: any): ProductSourceDto {
    return ProductSourceDtoFromJSONTyped(json, false);
}

export function ProductSourceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSourceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'source': json['source'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'price': json['price'] == null ? undefined : PriceDtoFromJSON(json['price']),
    };
}

export function ProductSourceDtoToJSON(value?: ProductSourceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'source': value['source'],
        'externalId': value['externalId'],
        'price': PriceDtoToJSON(value['price']),
    };
}

