/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSelectionListDto
 */
export interface ProductSelectionListDto {
    /**
     * 
     * @type {number}
     * @memberof ProductSelectionListDto
     */
    id: number;
    /**
     * Название подборки (макс. 60 символов)
     * @type {string}
     * @memberof ProductSelectionListDto
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductSelectionListDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ProductSelectionListDto interface.
 */
export function instanceOfProductSelectionListDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function ProductSelectionListDtoFromJSON(json: any): ProductSelectionListDto {
    return ProductSelectionListDtoFromJSONTyped(json, false);
}

export function ProductSelectionListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ProductSelectionListDtoToJSON(value?: ProductSelectionListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

