/* tslint:disable */
// eslint-disable-next-line unicorn/no-abusive-eslint-disable
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BasePropertyDto } from "./BasePropertyDto";
import {
  BasePropertyDtoFromJSON,
  BasePropertyDtoFromJSONTyped,
  BasePropertyDtoToJSON,
} from "./BasePropertyDto";
import type { BrandItemsModelDto } from "./BrandItemsModelDto";
import {
  BrandItemsModelDtoFromJSON,
  BrandItemsModelDtoFromJSONTyped,
  BrandItemsModelDtoToJSON,
} from "./BrandItemsModelDto";
import type { BuyDialogModelDto } from "./BuyDialogModelDto";
import {
  BuyDialogModelDtoFromJSON,
  BuyDialogModelDtoFromJSONTyped,
  BuyDialogModelDtoToJSON,
} from "./BuyDialogModelDto";
import type { PriceDto } from "./PriceDto";
import {
  PriceDtoFromJSON,
  PriceDtoFromJSONTyped,
  PriceDtoToJSON,
} from "./PriceDto";
import type { SaleImagesDto } from "./SaleImagesDto";
import {
  SaleImagesDtoFromJSON,
  SaleImagesDtoFromJSONTyped,
  SaleImagesDtoToJSON,
} from "./SaleImagesDto";
import type { ShareInfoDto } from "./ShareInfoDto";
import {
  ShareInfoDtoFromJSON,
  ShareInfoDtoFromJSONTyped,
  ShareInfoDtoToJSON,
} from "./ShareInfoDto";

export interface PropertyModuleItemDto {
  name: string;
  value: string;
}

export interface PropertyModuleBlockDto {
  propertyList: Array<PropertyModuleItemDto>;
  isShowTitle: boolean;
  title: string;
  type: string;
}

export interface PropertyModuleDto {
  propertyBlocks: Array<PropertyModuleBlockDto>;
  iconUrl: string;
}

/**
 *
 * @export
 * @interface ProductInfoResponseDto
 */
export interface ProductInfoResponseDto {
  /**
   *
   * @type {ShareInfoDto}
   * @memberof ProductInfoResponseDto
   */
  shareInfo: ShareInfoDto;
  /**
   *
   * @type {BrandItemsModelDto}
   * @memberof ProductInfoResponseDto
   */
  brandItemsModel: BrandItemsModelDto;
  /**
   *
   * @type {BuyDialogModelDto}
   * @memberof ProductInfoResponseDto
   */
  buyDialogModel: BuyDialogModelDto;
  /**
   *
   * @type {PriceDto}
   * @memberof ProductInfoResponseDto
   */
  price: PriceDto;
  /**
   *
   * @type {Array<BasePropertyDto>}
   * @memberof ProductInfoResponseDto
   */
  baseProperties: Array<BasePropertyDto>;
  /**
   *
   * @type {Array<SaleImagesDto>}
   * @memberof ProductInfoResponseDto
   */
  imageModels: Array<SaleImagesDto>;
  /**
   *
   * @type {PropertyModuleDto}
   * @memberof ProductInfoResponseDto
   */
  propertyModule?: PropertyModuleDto;
  /**
   *
   * @type {Array<BasePropertyDto>}
   * @memberof ProductInfoResponseDto
   */
  seriesItemsModel?: Array<BasePropertyDto>;

  rankingModule?: {
    rankingList: [
      {
        icon: string;
        name: string;
        rank: string;
        id: number;
        url: string;
      },
    ];
  };

  detailTextModule?: {
    detailTextList: {
      generalType: string;
      subTitle: string;
      imgEvenTrace: string;
      content: string;
    }[];
    title: string;
  };

  authenticatedGuaranteeModule?: {
    width: number;
    title: string;
    url: string;
    height: number;
  };

  detailImageList?: {
    imageId: number;
    sort: number;
    genericType: string;
    genericTypeSort: number;
    imgEvenTrace: string;
    url: string;
    imgType: number;
    burialImgType: number;
  }[];

  seriesDialogModel?: {
    seriesSpuList: {
      spuId: number;
      logoUrl: string;
    }[];
    dialogTitle: string;
    spuCount: number;
    dialogSeriesTitle: string;
    seriesId: number;
    dialogSeriesSpuCnt: string;
  };
}

/**
 * Check if a given object implements the ProductInfoResponseDto interface.
 */
export function instanceOfProductInfoResponseDto(value: object): boolean {
  if (!("shareInfo" in value)) return false;
  if (!("brandItemsModel" in value)) return false;
  if (!("buyDialogModel" in value)) return false;
  if (!("price" in value)) return false;
  if (!("baseProperties" in value)) return false;
  if (!("imageModels" in value)) return false;
  if (!("propertyModule" in value)) return false;
  return true;
}

export function ProductInfoResponseDtoFromJSON(
  json: any,
): ProductInfoResponseDto {
  return ProductInfoResponseDtoFromJSONTyped(json, false);
}

export function ProductInfoResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductInfoResponseDto {
  if (json == null) {
    return json;
  }
  return {
    shareInfo: ShareInfoDtoFromJSON(json["shareInfo"]),
    brandItemsModel: BrandItemsModelDtoFromJSON(json["brandItemsModel"]),
    buyDialogModel: BuyDialogModelDtoFromJSON(json["buyDialogModel"]),
    price: PriceDtoFromJSON(json["price"]),
    baseProperties: (json["baseProperties"] as Array<any>).map(
      BasePropertyDtoFromJSON,
    ),
    imageModels: (json["imageModels"] as Array<any>).map(SaleImagesDtoFromJSON),
    propertyModule: {
      propertyBlocks: (json["propertyModule"]?.propertyBlocks ?? []).map(
        (block: any): PropertyModuleBlockDto => ({
          propertyList: (block["propertyList"] ?? []).map(
            (item: any): PropertyModuleItemDto => ({
              name: item["name"],
              value: item["value"],
            }),
          ),
          isShowTitle: block["isShowTitle"],
          title: block["title"],
          type: block["type"],
        }),
      ),
      iconUrl: json["propertyModule"]?.iconUrl,
    },
    seriesItemsModel:
      json["seriesItemsModel"] == null
        ? undefined
        : (json["seriesItemsModel"] as Array<any>).map(BasePropertyDtoFromJSON),
  };
}

export function ProductInfoResponseDtoToJSON(
  value?: ProductInfoResponseDto | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    shareInfo: ShareInfoDtoToJSON(value["shareInfo"]),
    brandItemsModel: BrandItemsModelDtoToJSON(value["brandItemsModel"]),
    buyDialogModel: BuyDialogModelDtoToJSON(value["buyDialogModel"]),
    price: PriceDtoToJSON(value["price"]),
    baseProperties: (value["baseProperties"] as Array<any>).map(
      BasePropertyDtoToJSON,
    ),
    imageModels: (value["imageModels"] as Array<any>).map(SaleImagesDtoToJSON),
    propertyModule: {
      propertyBlocks: value["propertyModule"].propertyBlocks.map((block) => ({
        propertyList: block.propertyList.map((item) => ({
          name: item.name,
          value: item.value,
        })),
        isShowTitle: block.isShowTitle,
        title: block.title,
        type: block.type,
      })),
      iconUrl: value["propertyModule"].iconUrl,
    },
    seriesItemsModel:
      value["seriesItemsModel"] == null
        ? undefined
        : (value["seriesItemsModel"] as Array<any>).map(BasePropertyDtoToJSON),
  };
}
