/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaResponse } from './MetaResponse';
import {
    MetaResponseFromJSON,
    MetaResponseFromJSONTyped,
    MetaResponseToJSON,
} from './MetaResponse';
import type { ProductResponseDto } from './ProductResponseDto';
import {
    ProductResponseDtoFromJSON,
    ProductResponseDtoFromJSONTyped,
    ProductResponseDtoToJSON,
} from './ProductResponseDto';

/**
 * 
 * @export
 * @interface ProductsResponseWithPaginationDto
 */
export interface ProductsResponseWithPaginationDto {
    /**
     * 
     * @type {Array<ProductResponseDto>}
     * @memberof ProductsResponseWithPaginationDto
     */
    data: Array<ProductResponseDto>;
    /**
     * 
     * @type {MetaResponse}
     * @memberof ProductsResponseWithPaginationDto
     */
    meta: MetaResponse;
}

/**
 * Check if a given object implements the ProductsResponseWithPaginationDto interface.
 */
export function instanceOfProductsResponseWithPaginationDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ProductsResponseWithPaginationDtoFromJSON(json: any): ProductsResponseWithPaginationDto {
    return ProductsResponseWithPaginationDtoFromJSONTyped(json, false);
}

export function ProductsResponseWithPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsResponseWithPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProductResponseDtoFromJSON)),
        'meta': MetaResponseFromJSON(json['meta']),
    };
}

export function ProductsResponseWithPaginationDtoToJSON(value?: ProductsResponseWithPaginationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ProductResponseDtoToJSON)),
        'meta': MetaResponseToJSON(value['meta']),
    };
}

