/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaResponse } from './MetaResponse';
import {
    MetaResponseFromJSON,
    MetaResponseFromJSONTyped,
    MetaResponseToJSON,
} from './MetaResponse';
import type { ProductResponseV2Dto } from './ProductResponseV2Dto';
import {
    ProductResponseV2DtoFromJSON,
    ProductResponseV2DtoFromJSONTyped,
    ProductResponseV2DtoToJSON,
} from './ProductResponseV2Dto';

/**
 * 
 * @export
 * @interface ProductsResponseV2WithPaginationDto
 */
export interface ProductsResponseV2WithPaginationDto {
    /**
     * 
     * @type {Array<ProductResponseV2Dto>}
     * @memberof ProductsResponseV2WithPaginationDto
     */
    data: Array<ProductResponseV2Dto>;
    /**
     * 
     * @type {MetaResponse}
     * @memberof ProductsResponseV2WithPaginationDto
     */
    meta: MetaResponse;
}

/**
 * Check if a given object implements the ProductsResponseV2WithPaginationDto interface.
 */
export function instanceOfProductsResponseV2WithPaginationDto(value: object): boolean {
    if (!('data' in value)) return false;
    if (!('meta' in value)) return false;
    return true;
}

export function ProductsResponseV2WithPaginationDtoFromJSON(json: any): ProductsResponseV2WithPaginationDto {
    return ProductsResponseV2WithPaginationDtoFromJSONTyped(json, false);
}

export function ProductsResponseV2WithPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsResponseV2WithPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProductResponseV2DtoFromJSON)),
        'meta': MetaResponseFromJSON(json['meta']),
    };
}

export function ProductsResponseV2WithPaginationDtoToJSON(value?: ProductsResponseV2WithPaginationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ProductResponseV2DtoToJSON)),
        'meta': MetaResponseToJSON(value['meta']),
    };
}

