/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSelectionParamValuesDto
 */
export interface ProductSelectionParamValuesDto {
    /**
     * Уникальные значения свойств товаров выборки по заданным ключам. Отсортированы Intl.Collator("ru"). Длина ≤ limit.
     * @type {Array<string>}
     * @memberof ProductSelectionParamValuesDto
     */
    values: Array<string>;
    /**
     * true, если число уникальных значений после фильтра превысило limit и ответ был обрезан.
     * @type {boolean}
     * @memberof ProductSelectionParamValuesDto
     */
    truncated: boolean;
    /**
     * Общее число уникальных значений до обрезания по limit (после применения query-фильтра).
     * @type {number}
     * @memberof ProductSelectionParamValuesDto
     */
    totalCount: number;
}

/**
 * Check if a given object implements the ProductSelectionParamValuesDto interface.
 */
export function instanceOfProductSelectionParamValuesDto(value: object): boolean {
    if (!('values' in value)) return false;
    if (!('truncated' in value)) return false;
    if (!('totalCount' in value)) return false;
    return true;
}

export function ProductSelectionParamValuesDtoFromJSON(json: any): ProductSelectionParamValuesDto {
    return ProductSelectionParamValuesDtoFromJSONTyped(json, false);
}

export function ProductSelectionParamValuesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionParamValuesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'],
        'truncated': json['truncated'],
        'totalCount': json['totalCount'],
    };
}

export function ProductSelectionParamValuesDtoToJSON(value?: ProductSelectionParamValuesDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'values': value['values'],
        'truncated': value['truncated'],
        'totalCount': value['totalCount'],
    };
}

