/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSelectionCountDto
 */
export interface ProductSelectionCountDto {
    /**
     * Количество товаров в выборке
     * @type {number}
     * @memberof ProductSelectionCountDto
     */
    count: number;
}

/**
 * Check if a given object implements the ProductSelectionCountDto interface.
 */
export function instanceOfProductSelectionCountDto(value: object): boolean {
    if (!('count' in value)) return false;
    return true;
}

export function ProductSelectionCountDtoFromJSON(json: any): ProductSelectionCountDto {
    return ProductSelectionCountDtoFromJSONTyped(json, false);
}

export function ProductSelectionCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function ProductSelectionCountDtoToJSON(value?: ProductSelectionCountDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
    };
}

