/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSelectionDto
 */
export interface ProductSelectionDto {
    /**
     * Название подборки (макс. 60 символов)
     * @type {string}
     * @memberof ProductSelectionDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSelectionDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductSelectionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProductSelectionDto
     */
    productIds?: Array<number>;
}

/**
 * Check if a given object implements the ProductSelectionDto interface.
 */
export function instanceOfProductSelectionDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function ProductSelectionDtoFromJSON(json: any): ProductSelectionDto {
    return ProductSelectionDtoFromJSONTyped(json, false);
}

export function ProductSelectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'productIds': json['productIds'] == null ? undefined : json['productIds'],
    };
}

export function ProductSelectionDtoToJSON(value?: ProductSelectionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'productIds': value['productIds'],
    };
}

