/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductSourceDto } from './ProductSourceDto';
import {
    ProductSourceDtoFromJSON,
    ProductSourceDtoFromJSONTyped,
    ProductSourceDtoToJSON,
} from './ProductSourceDto';

/**
 * 
 * @export
 * @interface ProductResponseDto
 */
export interface ProductResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    article: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponseDto
     */
    isCustom: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    logoUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    gender: ProductResponseDtoGenderEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    favoriteCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    soldCount: number;
    /**
     * Популярность 0–100
     * @type {number}
     * @memberof ProductResponseDto
     */
    popularityScore: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    currency: ProductResponseDtoCurrencyEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    minPrice: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    maxPrice: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    brandId: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    categoryId: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDto
     */
    modelId: number;
    /**
     * Source
     * @type {string}
     * @memberof ProductResponseDto
     */
    mainSource: ProductResponseDtoMainSourceEnum;
    /**
     * Product sources
     * @type {Array<ProductSourceDto>}
     * @memberof ProductResponseDto
     */
    productSources: Array<ProductSourceDto>;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    title?: string;
}


/**
 * @export
 */
export const ProductResponseDtoGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductResponseDtoGenderEnum = typeof ProductResponseDtoGenderEnum[keyof typeof ProductResponseDtoGenderEnum];

/**
 * @export
 */
export const ProductResponseDtoCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type ProductResponseDtoCurrencyEnum = typeof ProductResponseDtoCurrencyEnum[keyof typeof ProductResponseDtoCurrencyEnum];

/**
 * @export
 */
export const ProductResponseDtoMainSourceEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductResponseDtoMainSourceEnum = typeof ProductResponseDtoMainSourceEnum[keyof typeof ProductResponseDtoMainSourceEnum];


/**
 * Check if a given object implements the ProductResponseDto interface.
 */
export function instanceOfProductResponseDto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('article' in value)) return false;
    if (!('isCustom' in value)) return false;
    if (!('description' in value)) return false;
    if (!('logoUrl' in value)) return false;
    if (!('gender' in value)) return false;
    if (!('favoriteCount' in value)) return false;
    if (!('soldCount' in value)) return false;
    if (!('popularityScore' in value)) return false;
    if (!('currency' in value)) return false;
    if (!('minPrice' in value)) return false;
    if (!('maxPrice' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('brandId' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('modelId' in value)) return false;
    if (!('mainSource' in value)) return false;
    if (!('productSources' in value)) return false;
    return true;
}

export function ProductResponseDtoFromJSON(json: any): ProductResponseDto {
    return ProductResponseDtoFromJSONTyped(json, false);
}

export function ProductResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'article': json['article'],
        'isCustom': json['isCustom'],
        'description': json['description'],
        'logoUrl': json['logoUrl'],
        'gender': json['gender'],
        'favoriteCount': json['favoriteCount'],
        'soldCount': json['soldCount'],
        'popularityScore': json['popularityScore'],
        'currency': json['currency'],
        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'brandId': json['brandId'],
        'categoryId': json['categoryId'],
        'modelId': json['modelId'],
        'mainSource': json['mainSource'],
        'productSources': ((json['productSources'] as Array<any>).map(ProductSourceDtoFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ProductResponseDtoToJSON(value?: ProductResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'article': value['article'],
        'isCustom': value['isCustom'],
        'description': value['description'],
        'logoUrl': value['logoUrl'],
        'gender': value['gender'],
        'favoriteCount': value['favoriteCount'],
        'soldCount': value['soldCount'],
        'popularityScore': value['popularityScore'],
        'currency': value['currency'],
        'minPrice': value['minPrice'],
        'maxPrice': value['maxPrice'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'brandId': value['brandId'],
        'categoryId': value['categoryId'],
        'modelId': value['modelId'],
        'mainSource': value['mainSource'],
        'productSources': ((value['productSources'] as Array<any>).map(ProductSourceDtoToJSON)),
        'title': value['title'],
    };
}

