/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSelectionParamKeysDto
 */
export interface ProductSelectionParamKeysDto {
    /**
     * Уникальные ключи свойств (properties.key) по всем товарам выборки, отсортированы по алфавиту
     * @type {Array<string>}
     * @memberof ProductSelectionParamKeysDto
     */
    keys: Array<string>;
}

/**
 * Check if a given object implements the ProductSelectionParamKeysDto interface.
 */
export function instanceOfProductSelectionParamKeysDto(value: object): boolean {
    if (!('keys' in value)) return false;
    return true;
}

export function ProductSelectionParamKeysDtoFromJSON(json: any): ProductSelectionParamKeysDto {
    return ProductSelectionParamKeysDtoFromJSONTyped(json, false);
}

export function ProductSelectionParamKeysDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSelectionParamKeysDto {
    if (json == null) {
        return json;
    }
    return {
        
        'keys': json['keys'],
    };
}

export function ProductSelectionParamKeysDtoToJSON(value?: ProductSelectionParamKeysDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'keys': value['keys'],
    };
}

