/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Source } from './Source';
import {
    SourceFromJSON,
    SourceFromJSONTyped,
    SourceToJSON,
} from './Source';

/**
 * 
 * @export
 * @interface ProductResponseV2Dto
 */
export interface ProductResponseV2Dto {
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    article: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponseV2Dto
     */
    isCustom: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    logoUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    gender: ProductResponseV2DtoGenderEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    favoriteCount: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    soldCount: number;
    /**
     * Популярность 0–100
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    popularityScore: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    currency: ProductResponseV2DtoCurrencyEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    minPrice: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    maxPrice: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseV2Dto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseV2Dto
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    brandId: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    categoryId: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseV2Dto
     */
    modelId: number;
    /**
     * Source
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    mainSource: ProductResponseV2DtoMainSourceEnum;
    /**
     * 
     * @type {Array<Source>}
     * @memberof ProductResponseV2Dto
     */
    sources: Array<Source>;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseV2Dto
     */
    title?: string;
}


/**
 * @export
 */
export const ProductResponseV2DtoGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductResponseV2DtoGenderEnum = typeof ProductResponseV2DtoGenderEnum[keyof typeof ProductResponseV2DtoGenderEnum];

/**
 * @export
 */
export const ProductResponseV2DtoCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type ProductResponseV2DtoCurrencyEnum = typeof ProductResponseV2DtoCurrencyEnum[keyof typeof ProductResponseV2DtoCurrencyEnum];

/**
 * @export
 */
export const ProductResponseV2DtoMainSourceEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductResponseV2DtoMainSourceEnum = typeof ProductResponseV2DtoMainSourceEnum[keyof typeof ProductResponseV2DtoMainSourceEnum];


/**
 * Check if a given object implements the ProductResponseV2Dto interface.
 */
export function instanceOfProductResponseV2Dto(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('article' in value)) return false;
    if (!('isCustom' in value)) return false;
    if (!('logoUrl' in value)) return false;
    if (!('gender' in value)) return false;
    if (!('favoriteCount' in value)) return false;
    if (!('soldCount' in value)) return false;
    if (!('popularityScore' in value)) return false;
    if (!('currency' in value)) return false;
    if (!('minPrice' in value)) return false;
    if (!('maxPrice' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('brandId' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('modelId' in value)) return false;
    if (!('mainSource' in value)) return false;
    if (!('sources' in value)) return false;
    return true;
}

export function ProductResponseV2DtoFromJSON(json: any): ProductResponseV2Dto {
    return ProductResponseV2DtoFromJSONTyped(json, false);
}

export function ProductResponseV2DtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponseV2Dto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'article': json['article'],
        'isCustom': json['isCustom'],
        'logoUrl': json['logoUrl'],
        'gender': json['gender'],
        'favoriteCount': json['favoriteCount'],
        'soldCount': json['soldCount'],
        'popularityScore': json['popularityScore'],
        'currency': json['currency'],
        'minPrice': json['minPrice'],
        'maxPrice': json['maxPrice'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'brandId': json['brandId'],
        'categoryId': json['categoryId'],
        'modelId': json['modelId'],
        'mainSource': json['mainSource'],
        'sources': ((json['sources'] as Array<any>).map(SourceFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ProductResponseV2DtoToJSON(value?: ProductResponseV2Dto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'article': value['article'],
        'isCustom': value['isCustom'],
        'logoUrl': value['logoUrl'],
        'gender': value['gender'],
        'favoriteCount': value['favoriteCount'],
        'soldCount': value['soldCount'],
        'popularityScore': value['popularityScore'],
        'currency': value['currency'],
        'minPrice': value['minPrice'],
        'maxPrice': value['maxPrice'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'brandId': value['brandId'],
        'categoryId': value['categoryId'],
        'modelId': value['modelId'],
        'mainSource': value['mainSource'],
        'sources': ((value['sources'] as Array<any>).map(SourceToJSON)),
        'title': value['title'],
    };
}

