/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyItemModelDto } from './PropertyItemModelDto';
import {
    PropertyItemModelDtoFromJSON,
    PropertyItemModelDtoFromJSONTyped,
    PropertyItemModelDtoToJSON,
} from './PropertyItemModelDto';

/**
 * 
 * @export
 * @interface PropertyListDto
 */
export interface PropertyListDto {
    /**
     * 
     * @type {string}
     * @memberof PropertyListDto
     */
    propertyKey: string;
    /**
     * 
     * @type {Array<PropertyItemModelDto>}
     * @memberof PropertyListDto
     */
    propertyItemModels: Array<PropertyItemModelDto>;
}

/**
 * Check if a given object implements the PropertyListDto interface.
 */
export function instanceOfPropertyListDto(value: object): boolean {
    if (!('propertyKey' in value)) return false;
    if (!('propertyItemModels' in value)) return false;
    return true;
}

export function PropertyListDtoFromJSON(json: any): PropertyListDto {
    return PropertyListDtoFromJSONTyped(json, false);
}

export function PropertyListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyKey': json['propertyKey'],
        'propertyItemModels': ((json['propertyItemModels'] as Array<any>).map(PropertyItemModelDtoFromJSON)),
    };
}

export function PropertyListDtoToJSON(value?: PropertyListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'propertyKey': value['propertyKey'],
        'propertyItemModels': ((value['propertyItemModels'] as Array<any>).map(PropertyItemModelDtoToJSON)),
    };
}

