/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyItemModelDto
 */
export interface PropertyItemModelDto {
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    propertyValueId: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyItemModelDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    spuId: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    sort: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    propertyId: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyItemModelDto
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof PropertyItemModelDto
     */
    selected: boolean;
    /**
     * 
     * @type {number}
     * @memberof PropertyItemModelDto
     */
    definitionId: number;
    /**
     * 
     * @type {string}
     * @memberof PropertyItemModelDto
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyItemModelDto
     */
    suffix?: string;
}

/**
 * Check if a given object implements the PropertyItemModelDto interface.
 */
export function instanceOfPropertyItemModelDto(value: object): boolean {
    if (!('level' in value)) return false;
    if (!('propertyValueId' in value)) return false;
    if (!('name' in value)) return false;
    if (!('spuId' in value)) return false;
    if (!('sort' in value)) return false;
    if (!('propertyId' in value)) return false;
    if (!('value' in value)) return false;
    if (!('selected' in value)) return false;
    if (!('definitionId' in value)) return false;
    return true;
}

export function PropertyItemModelDtoFromJSON(json: any): PropertyItemModelDto {
    return PropertyItemModelDtoFromJSONTyped(json, false);
}

export function PropertyItemModelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyItemModelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'],
        'propertyValueId': json['propertyValueId'],
        'name': json['name'],
        'spuId': json['spuId'],
        'sort': json['sort'],
        'propertyId': json['propertyId'],
        'value': json['value'],
        'selected': json['selected'],
        'definitionId': json['definitionId'],
        'url': json['url'] == null ? undefined : json['url'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function PropertyItemModelDtoToJSON(value?: PropertyItemModelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'level': value['level'],
        'propertyValueId': value['propertyValueId'],
        'name': value['name'],
        'spuId': value['spuId'],
        'sort': value['sort'],
        'propertyId': value['propertyId'],
        'value': value['value'],
        'selected': value['selected'],
        'definitionId': value['definitionId'],
        'url': value['url'],
        'suffix': value['suffix'],
    };
}

