/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyDto
 */
export interface PropertyDto {
    /**
     * Ключ свойства
     * @type {string}
     * @memberof PropertyDto
     */
    key: string;
    /**
     * Значение свойства
     * @type {string}
     * @memberof PropertyDto
     */
    value: string;
    /**
     * ID свойства
     * @type {number}
     * @memberof PropertyDto
     */
    id?: number;
}

/**
 * Check if a given object implements the PropertyDto interface.
 */
export function instanceOfPropertyDto(value: object): boolean {
    if (!('key' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function PropertyDtoFromJSON(json: any): PropertyDto {
    return PropertyDtoFromJSONTyped(json, false);
}

export function PropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PropertyDtoToJSON(value?: PropertyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
        'id': value['id'],
    };
}

