/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyDto
 */
export interface PropertyDto {
    /**
     * 
     * @type {number}
     * @memberof PropertyDto
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyDto
     */
    propertyValueId: number;
}

/**
 * Check if a given object implements the PropertyDto interface.
 */
export function instanceOfPropertyDto(value: object): boolean {
    if (!('level' in value)) return false;
    if (!('propertyValueId' in value)) return false;
    return true;
}

export function PropertyDtoFromJSON(json: any): PropertyDto {
    return PropertyDtoFromJSONTyped(json, false);
}

export function PropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'],
        'propertyValueId': json['propertyValueId'],
    };
}

export function PropertyDtoToJSON(value?: PropertyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'level': value['level'],
        'propertyValueId': value['propertyValueId'],
    };
}

