/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecommendSizeDto
 */
export interface RecommendSizeDto {
    /**
     * 
     * @type {boolean}
     * @memberof RecommendSizeDto
     */
    showRecommendEnter: boolean;
}

/**
 * Check if a given object implements the RecommendSizeDto interface.
 */
export function instanceOfRecommendSizeDto(value: object): boolean {
    if (!('showRecommendEnter' in value)) return false;
    return true;
}

export function RecommendSizeDtoFromJSON(json: any): RecommendSizeDto {
    return RecommendSizeDtoFromJSONTyped(json, false);
}

export function RecommendSizeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendSizeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'showRecommendEnter': json['showRecommendEnter'],
    };
}

export function RecommendSizeDtoToJSON(value?: RecommendSizeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'showRecommendEnter': value['showRecommendEnter'],
    };
}

