/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewBodyParamDto
 */
export interface ReviewBodyParamDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewBodyParamDto
     */
    questionName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewBodyParamDto
     */
    optionContent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewBodyParamDto
     */
    isJumpSpuFlag?: boolean;
}

/**
 * Check if a given object implements the ReviewBodyParamDto interface.
 */
export function instanceOfReviewBodyParamDto(value: object): boolean {
    return true;
}

export function ReviewBodyParamDtoFromJSON(json: any): ReviewBodyParamDto {
    return ReviewBodyParamDtoFromJSONTyped(json, false);
}

export function ReviewBodyParamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewBodyParamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'questionName': json['questionName'] == null ? undefined : json['questionName'],
        'optionContent': json['optionContent'] == null ? undefined : json['optionContent'],
        'isJumpSpuFlag': json['isJumpSpuFlag'] == null ? undefined : json['isJumpSpuFlag'],
    };
}

export function ReviewBodyParamDtoToJSON(value?: ReviewBodyParamDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'questionName': value['questionName'],
        'optionContent': value['optionContent'],
        'isJumpSpuFlag': value['isJumpSpuFlag'],
    };
}

