/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewSizeFeelingDto
 */
export interface ReviewSizeFeelingDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewSizeFeelingDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewSizeFeelingDto
     */
    rateText?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewSizeFeelingDto
     */
    thousandRate?: number;
}

/**
 * Check if a given object implements the ReviewSizeFeelingDto interface.
 */
export function instanceOfReviewSizeFeelingDto(value: object): boolean {
    return true;
}

export function ReviewSizeFeelingDtoFromJSON(json: any): ReviewSizeFeelingDto {
    return ReviewSizeFeelingDtoFromJSONTyped(json, false);
}

export function ReviewSizeFeelingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSizeFeelingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'rateText': json['rateText'] == null ? undefined : json['rateText'],
        'thousandRate': json['thousandRate'] == null ? undefined : json['thousandRate'],
    };
}

export function ReviewSizeFeelingDtoToJSON(value?: ReviewSizeFeelingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'rateText': value['rateText'],
        'thousandRate': value['thousandRate'],
    };
}

