/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewImageDto
 */
export interface ReviewImageDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewImageDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewImageDto
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewImageDto
     */
    height?: number;
}

/**
 * Check if a given object implements the ReviewImageDto interface.
 */
export function instanceOfReviewImageDto(value: object): boolean {
    return true;
}

export function ReviewImageDtoFromJSON(json: any): ReviewImageDto {
    return ReviewImageDtoFromJSONTyped(json, false);
}

export function ReviewImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function ReviewImageDtoToJSON(value?: ReviewImageDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'imageUrl': value['imageUrl'],
        'width': value['width'],
        'height': value['height'],
    };
}

