/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewBodyParamDto } from './ReviewBodyParamDto';
import {
    ReviewBodyParamDtoFromJSON,
    ReviewBodyParamDtoFromJSONTyped,
    ReviewBodyParamDtoToJSON,
} from './ReviewBodyParamDto';
import type { ReviewImageDto } from './ReviewImageDto';
import {
    ReviewImageDtoFromJSON,
    ReviewImageDtoFromJSONTyped,
    ReviewImageDtoToJSON,
} from './ReviewImageDto';
import type { ReviewProductPropertyDto } from './ReviewProductPropertyDto';
import {
    ReviewProductPropertyDtoFromJSON,
    ReviewProductPropertyDtoFromJSONTyped,
    ReviewProductPropertyDtoToJSON,
} from './ReviewProductPropertyDto';

/**
 * 
 * @export
 * @interface ReviewItemDto
 */
export interface ReviewItemDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    reviewId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    defaultIcon?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewItemDto
     */
    hasImage?: number;
    /**
     * 
     * @type {Array<ReviewImageDto>}
     * @memberof ReviewItemDto
     */
    images?: Array<ReviewImageDto>;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    publishDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    poizonReply?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReviewItemDto
     */
    reviewData?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    score?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    skuProperty?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    userIcon?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewItemDto
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    firstLetter?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewItemDto
     */
    spuId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    fromOtherLang?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    sizeFeelingText?: string;
    /**
     * 
     * @type {Array<ReviewBodyParamDto>}
     * @memberof ReviewItemDto
     */
    bodyParamList?: Array<ReviewBodyParamDto>;
    /**
     * 
     * @type {Array<ReviewProductPropertyDto>}
     * @memberof ReviewItemDto
     */
    productParamList?: Array<ReviewProductPropertyDto>;
    /**
     * 
     * @type {number}
     * @memberof ReviewItemDto
     */
    originType?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    spuLink?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    trackingId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewItemDto
     */
    contentId?: string;
}

/**
 * Check if a given object implements the ReviewItemDto interface.
 */
export function instanceOfReviewItemDto(value: object): boolean {
    return true;
}

export function ReviewItemDtoFromJSON(json: any): ReviewItemDto {
    return ReviewItemDtoFromJSONTyped(json, false);
}

export function ReviewItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewId': json['reviewId'] == null ? undefined : json['reviewId'],
        'defaultIcon': json['defaultIcon'] == null ? undefined : json['defaultIcon'],
        'hasImage': json['hasImage'] == null ? undefined : json['hasImage'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ReviewImageDtoFromJSON)),
        'publishDate': json['publishDate'] == null ? undefined : json['publishDate'],
        'poizonReply': json['poizonReply'] == null ? undefined : json['poizonReply'],
        'reviewData': json['reviewData'] == null ? undefined : json['reviewData'],
        'score': json['score'] == null ? undefined : json['score'],
        'skuProperty': json['skuProperty'] == null ? undefined : json['skuProperty'],
        'userIcon': json['userIcon'] == null ? undefined : json['userIcon'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'firstLetter': json['firstLetter'] == null ? undefined : json['firstLetter'],
        'spuId': json['spuId'] == null ? undefined : json['spuId'],
        'fromOtherLang': json['fromOtherLang'] == null ? undefined : json['fromOtherLang'],
        'sizeFeelingText': json['sizeFeelingText'] == null ? undefined : json['sizeFeelingText'],
        'bodyParamList': json['bodyParamList'] == null ? undefined : ((json['bodyParamList'] as Array<any>).map(ReviewBodyParamDtoFromJSON)),
        'productParamList': json['productParamList'] == null ? undefined : ((json['productParamList'] as Array<any>).map(ReviewProductPropertyDtoFromJSON)),
        'originType': json['originType'] == null ? undefined : json['originType'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'spuLink': json['spuLink'] == null ? undefined : json['spuLink'],
        'trackingId': json['trackingId'] == null ? undefined : json['trackingId'],
        'contentId': json['contentId'] == null ? undefined : json['contentId'],
    };
}

export function ReviewItemDtoToJSON(value?: ReviewItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reviewId': value['reviewId'],
        'defaultIcon': value['defaultIcon'],
        'hasImage': value['hasImage'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ReviewImageDtoToJSON)),
        'publishDate': value['publishDate'],
        'poizonReply': value['poizonReply'],
        'reviewData': value['reviewData'],
        'score': value['score'],
        'skuProperty': value['skuProperty'],
        'userIcon': value['userIcon'],
        'userId': value['userId'],
        'userName': value['userName'],
        'firstLetter': value['firstLetter'],
        'spuId': value['spuId'],
        'fromOtherLang': value['fromOtherLang'],
        'sizeFeelingText': value['sizeFeelingText'],
        'bodyParamList': value['bodyParamList'] == null ? undefined : ((value['bodyParamList'] as Array<any>).map(ReviewBodyParamDtoToJSON)),
        'productParamList': value['productParamList'] == null ? undefined : ((value['productParamList'] as Array<any>).map(ReviewProductPropertyDtoToJSON)),
        'originType': value['originType'],
        'categoryId': value['categoryId'],
        'spuLink': value['spuLink'],
        'trackingId': value['trackingId'],
        'contentId': value['contentId'],
    };
}

