/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewProductPropertyDto
 */
export interface ReviewProductPropertyDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewProductPropertyDto
     */
    frontLocalName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewProductPropertyDto
     */
    frontLocalValue?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewProductPropertyDto
     */
    isJumpSpuFlag?: boolean;
}

/**
 * Check if a given object implements the ReviewProductPropertyDto interface.
 */
export function instanceOfReviewProductPropertyDto(value: object): boolean {
    return true;
}

export function ReviewProductPropertyDtoFromJSON(json: any): ReviewProductPropertyDto {
    return ReviewProductPropertyDtoFromJSONTyped(json, false);
}

export function ReviewProductPropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewProductPropertyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'frontLocalName': json['frontLocalName'] == null ? undefined : json['frontLocalName'],
        'frontLocalValue': json['frontLocalValue'] == null ? undefined : json['frontLocalValue'],
        'isJumpSpuFlag': json['isJumpSpuFlag'] == null ? undefined : json['isJumpSpuFlag'],
    };
}

export function ReviewProductPropertyDtoToJSON(value?: ReviewProductPropertyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'frontLocalName': value['frontLocalName'],
        'frontLocalValue': value['frontLocalValue'],
        'isJumpSpuFlag': value['isJumpSpuFlag'],
    };
}

