/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewExtraDto } from './ReviewExtraDto';
import {
    ReviewExtraDtoFromJSON,
    ReviewExtraDtoFromJSONTyped,
    ReviewExtraDtoToJSON,
} from './ReviewExtraDto';
import type { ReviewItemDto } from './ReviewItemDto';
import {
    ReviewItemDtoFromJSON,
    ReviewItemDtoFromJSONTyped,
    ReviewItemDtoToJSON,
} from './ReviewItemDto';

/**
 * 
 * @export
 * @interface ReviewListResponseDto
 */
export interface ReviewListResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    lastId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    pageNum?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    pages?: number;
    /**
     * 
     * @type {Array<ReviewItemDto>}
     * @memberof ReviewListResponseDto
     */
    contents?: Array<ReviewItemDto>;
    /**
     * 
     * @type {Array<ReviewItemDto>}
     * @memberof ReviewListResponseDto
     */
    otherReviewsItems?: Array<ReviewItemDto>;
    /**
     * 
     * @type {ReviewExtraDto}
     * @memberof ReviewListResponseDto
     */
    extra?: ReviewExtraDto;
    /**
     * 
     * @type {string}
     * @memberof ReviewListResponseDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewListResponseDto
     */
    scope?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ReviewListResponseDto
     */
    spuId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewListResponseDto
     */
    scoreDes?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewListResponseDto
     */
    feedTitle?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewListResponseDto
     */
    fromOtherRegion?: boolean;
}

/**
 * Check if a given object implements the ReviewListResponseDto interface.
 */
export function instanceOfReviewListResponseDto(value: object): boolean {
    return true;
}

export function ReviewListResponseDtoFromJSON(json: any): ReviewListResponseDto {
    return ReviewListResponseDtoFromJSONTyped(json, false);
}

export function ReviewListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lastId': json['lastId'] == null ? undefined : json['lastId'],
        'pageNum': json['pageNum'] == null ? undefined : json['pageNum'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'contents': json['contents'] == null ? undefined : ((json['contents'] as Array<any>).map(ReviewItemDtoFromJSON)),
        'otherReviewsItems': json['otherReviewsItems'] == null ? undefined : ((json['otherReviewsItems'] as Array<any>).map(ReviewItemDtoFromJSON)),
        'extra': json['extra'] == null ? undefined : ReviewExtraDtoFromJSON(json['extra']),
        'title': json['title'] == null ? undefined : json['title'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'total': json['total'] == null ? undefined : json['total'],
        'spuId': json['spuId'] == null ? undefined : json['spuId'],
        'scoreDes': json['scoreDes'] == null ? undefined : json['scoreDes'],
        'feedTitle': json['feedTitle'] == null ? undefined : json['feedTitle'],
        'fromOtherRegion': json['fromOtherRegion'] == null ? undefined : json['fromOtherRegion'],
    };
}

export function ReviewListResponseDtoToJSON(value?: ReviewListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lastId': value['lastId'],
        'pageNum': value['pageNum'],
        'pageSize': value['pageSize'],
        'pages': value['pages'],
        'contents': value['contents'] == null ? undefined : ((value['contents'] as Array<any>).map(ReviewItemDtoToJSON)),
        'otherReviewsItems': value['otherReviewsItems'] == null ? undefined : ((value['otherReviewsItems'] as Array<any>).map(ReviewItemDtoToJSON)),
        'extra': ReviewExtraDtoToJSON(value['extra']),
        'title': value['title'],
        'scope': value['scope'],
        'total': value['total'],
        'spuId': value['spuId'],
        'scoreDes': value['scoreDes'],
        'feedTitle': value['feedTitle'],
        'fromOtherRegion': value['fromOtherRegion'],
    };
}

