/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewItemDto } from './ReviewItemDto';
import {
    ReviewItemDtoFromJSON,
    ReviewItemDtoFromJSONTyped,
    ReviewItemDtoToJSON,
} from './ReviewItemDto';
import type { ReviewSizeFeelingDto } from './ReviewSizeFeelingDto';
import {
    ReviewSizeFeelingDtoFromJSON,
    ReviewSizeFeelingDtoFromJSONTyped,
    ReviewSizeFeelingDtoToJSON,
} from './ReviewSizeFeelingDto';

/**
 * 
 * @export
 * @interface ReviewExtraDto
 */
export interface ReviewExtraDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    count?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    desc?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    score?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    scoreNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    noResultWithSpuMsg?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    noResultWithMyBodyMsg?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    noResultWithMultiFilterMsg?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    feedTitle?: string;
    /**
     * 
     * @type {Array<ReviewSizeFeelingDto>}
     * @memberof ReviewExtraDto
     */
    sizeFeelingModule?: Array<ReviewSizeFeelingDto>;
    /**
     * 
     * @type {Array<ReviewItemDto>}
     * @memberof ReviewExtraDto
     */
    hideReviews?: Array<ReviewItemDto>;
    /**
     * 
     * @type {Array<ReviewItemDto>}
     * @memberof ReviewExtraDto
     */
    otherHideReviews?: Array<ReviewItemDto>;
    /**
     * 
     * @type {string}
     * @memberof ReviewExtraDto
     */
    aiSummary?: string;
}

/**
 * Check if a given object implements the ReviewExtraDto interface.
 */
export function instanceOfReviewExtraDto(value: object): boolean {
    return true;
}

export function ReviewExtraDtoFromJSON(json: any): ReviewExtraDto {
    return ReviewExtraDtoFromJSONTyped(json, false);
}

export function ReviewExtraDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewExtraDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'count': json['count'] == null ? undefined : json['count'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'score': json['score'] == null ? undefined : json['score'],
        'scoreNumber': json['scoreNumber'] == null ? undefined : json['scoreNumber'],
        'noResultWithSpuMsg': json['noResultWithSpuMsg'] == null ? undefined : json['noResultWithSpuMsg'],
        'noResultWithMyBodyMsg': json['noResultWithMyBodyMsg'] == null ? undefined : json['noResultWithMyBodyMsg'],
        'noResultWithMultiFilterMsg': json['noResultWithMultiFilterMsg'] == null ? undefined : json['noResultWithMultiFilterMsg'],
        'feedTitle': json['feedTitle'] == null ? undefined : json['feedTitle'],
        'sizeFeelingModule': json['sizeFeelingModule'] == null ? undefined : ((json['sizeFeelingModule'] as Array<any>).map(ReviewSizeFeelingDtoFromJSON)),
        'hideReviews': json['hideReviews'] == null ? undefined : ((json['hideReviews'] as Array<any>).map(ReviewItemDtoFromJSON)),
        'otherHideReviews': json['otherHideReviews'] == null ? undefined : ((json['otherHideReviews'] as Array<any>).map(ReviewItemDtoFromJSON)),
        'aiSummary': json['aiSummary'] == null ? undefined : json['aiSummary'],
    };
}

export function ReviewExtraDtoToJSON(value?: ReviewExtraDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'count': value['count'],
        'categoryId': value['categoryId'],
        'desc': value['desc'],
        'score': value['score'],
        'scoreNumber': value['scoreNumber'],
        'noResultWithSpuMsg': value['noResultWithSpuMsg'],
        'noResultWithMyBodyMsg': value['noResultWithMyBodyMsg'],
        'noResultWithMultiFilterMsg': value['noResultWithMultiFilterMsg'],
        'feedTitle': value['feedTitle'],
        'sizeFeelingModule': value['sizeFeelingModule'] == null ? undefined : ((value['sizeFeelingModule'] as Array<any>).map(ReviewSizeFeelingDtoToJSON)),
        'hideReviews': value['hideReviews'] == null ? undefined : ((value['hideReviews'] as Array<any>).map(ReviewItemDtoToJSON)),
        'otherHideReviews': value['otherHideReviews'] == null ? undefined : ((value['otherHideReviews'] as Array<any>).map(ReviewItemDtoToJSON)),
        'aiSummary': value['aiSummary'],
    };
}

