/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyListDto } from './PropertyListDto';
import {
    PropertyListDtoFromJSON,
    PropertyListDtoFromJSONTyped,
    PropertyListDtoToJSON,
} from './PropertyListDto';

/**
 * 
 * @export
 * @interface SalePropertyDto
 */
export interface SalePropertyDto {
    /**
     * 
     * @type {number}
     * @memberof SalePropertyDto
     */
    displayStyle: number;
    /**
     * 
     * @type {number}
     * @memberof SalePropertyDto
     */
    level: number;
    /**
     * 
     * @type {Array<PropertyListDto>}
     * @memberof SalePropertyDto
     */
    propertyList: Array<PropertyListDto>;
    /**
     * 
     * @type {string}
     * @memberof SalePropertyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SalePropertyDto
     */
    defaultShow: string;
    /**
     * 
     * @type {number}
     * @memberof SalePropertyDto
     */
    governType: number;
    /**
     * 
     * @type {boolean}
     * @memberof SalePropertyDto
     */
    giftProp: boolean;
    /**
     * 
     * @type {number}
     * @memberof SalePropertyDto
     */
    definitionId: number;
    /**
     * 
     * @type {string}
     * @memberof SalePropertyDto
     */
    guideTip?: string;
    /**
     * 
     * @type {number}
     * @memberof SalePropertyDto
     */
    showGuide?: number;
    /**
     * 
     * @type {string}
     * @memberof SalePropertyDto
     */
    deviationCodePrompt?: string;
}

/**
 * Check if a given object implements the SalePropertyDto interface.
 */
export function instanceOfSalePropertyDto(value: object): boolean {
    if (!('displayStyle' in value)) return false;
    if (!('level' in value)) return false;
    if (!('propertyList' in value)) return false;
    if (!('name' in value)) return false;
    if (!('defaultShow' in value)) return false;
    if (!('governType' in value)) return false;
    if (!('giftProp' in value)) return false;
    if (!('definitionId' in value)) return false;
    return true;
}

export function SalePropertyDtoFromJSON(json: any): SalePropertyDto {
    return SalePropertyDtoFromJSONTyped(json, false);
}

export function SalePropertyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalePropertyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'displayStyle': json['displayStyle'],
        'level': json['level'],
        'propertyList': ((json['propertyList'] as Array<any>).map(PropertyListDtoFromJSON)),
        'name': json['name'],
        'defaultShow': json['defaultShow'],
        'governType': json['governType'],
        'giftProp': json['giftProp'],
        'definitionId': json['definitionId'],
        'guideTip': json['guideTip'] == null ? undefined : json['guideTip'],
        'showGuide': json['showGuide'] == null ? undefined : json['showGuide'],
        'deviationCodePrompt': json['deviationCodePrompt'] == null ? undefined : json['deviationCodePrompt'],
    };
}

export function SalePropertyDtoToJSON(value?: SalePropertyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayStyle': value['displayStyle'],
        'level': value['level'],
        'propertyList': ((value['propertyList'] as Array<any>).map(PropertyListDtoToJSON)),
        'name': value['name'],
        'defaultShow': value['defaultShow'],
        'governType': value['governType'],
        'giftProp': value['giftProp'],
        'definitionId': value['definitionId'],
        'guideTip': value['guideTip'],
        'showGuide': value['showGuide'],
        'deviationCodePrompt': value['deviationCodePrompt'],
    };
}

