/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaleImagesDto
 */
export interface SaleImagesDto {
    /**
     * 
     * @type {boolean}
     * @memberof SaleImagesDto
     */
    modelWear: boolean;
    /**
     * 
     * @type {number}
     * @memberof SaleImagesDto
     */
    imageId: number;
    /**
     * 
     * @type {number}
     * @memberof SaleImagesDto
     */
    propertyValueId: number;
    /**
     * 
     * @type {string}
     * @memberof SaleImagesDto
     */
    colorStyle: string;
    /**
     * 
     * @type {number}
     * @memberof SaleImagesDto
     */
    channel: number;
    /**
     * 
     * @type {number}
     * @memberof SaleImagesDto
     */
    sort: number;
    /**
     * 
     * @type {string}
     * @memberof SaleImagesDto
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof SaleImagesDto
     */
    imgType: number;
}

/**
 * Check if a given object implements the SaleImagesDto interface.
 */
export function instanceOfSaleImagesDto(value: object): boolean {
    if (!('modelWear' in value)) return false;
    if (!('imageId' in value)) return false;
    if (!('propertyValueId' in value)) return false;
    if (!('colorStyle' in value)) return false;
    if (!('channel' in value)) return false;
    if (!('sort' in value)) return false;
    if (!('url' in value)) return false;
    if (!('imgType' in value)) return false;
    return true;
}

export function SaleImagesDtoFromJSON(json: any): SaleImagesDto {
    return SaleImagesDtoFromJSONTyped(json, false);
}

export function SaleImagesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaleImagesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'modelWear': json['modelWear'],
        'imageId': json['imageId'],
        'propertyValueId': json['propertyValueId'],
        'colorStyle': json['colorStyle'],
        'channel': json['channel'],
        'sort': json['sort'],
        'url': json['url'],
        'imgType': json['imgType'],
    };
}

export function SaleImagesDtoToJSON(value?: SaleImagesDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'modelWear': value['modelWear'],
        'imageId': value['imageId'],
        'propertyValueId': value['propertyValueId'],
        'colorStyle': value['colorStyle'],
        'channel': value['channel'],
        'sort': value['sort'],
        'url': value['url'],
        'imgType': value['imgType'],
    };
}

