/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchProductsCountResponseDto
 */
export interface SearchProductsCountResponseDto {
    /**
     * 
     * @type {number}
     * @memberof SearchProductsCountResponseDto
     */
    count: number;
}

/**
 * Check if a given object implements the SearchProductsCountResponseDto interface.
 */
export function instanceOfSearchProductsCountResponseDto(value: object): boolean {
    if (!('count' in value)) return false;
    return true;
}

export function SearchProductsCountResponseDtoFromJSON(json: any): SearchProductsCountResponseDto {
    return SearchProductsCountResponseDtoFromJSONTyped(json, false);
}

export function SearchProductsCountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchProductsCountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function SearchProductsCountResponseDtoToJSON(value?: SearchProductsCountResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
    };
}

