/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlgoAcmDto } from './AlgoAcmDto';
import {
    AlgoAcmDtoFromJSON,
    AlgoAcmDtoFromJSONTyped,
    AlgoAcmDtoToJSON,
} from './AlgoAcmDto';
import type { SpuListItemDto } from './SpuListItemDto';
import {
    SpuListItemDtoFromJSON,
    SpuListItemDtoFromJSONTyped,
    SpuListItemDtoToJSON,
} from './SpuListItemDto';

/**
 * 
 * @export
 * @interface SearchSpuListDto
 */
export interface SearchSpuListDto {
    /**
     * 
     * @type {number}
     * @memberof SearchSpuListDto
     */
    total: number;
    /**
     * 
     * @type {Array<SpuListItemDto>}
     * @memberof SearchSpuListDto
     */
    spuList: Array<SpuListItemDto>;
    /**
     * 
     * @type {AlgoAcmDto}
     * @memberof SearchSpuListDto
     */
    algoAcmDto: AlgoAcmDto;
    /**
     * 
     * @type {string}
     * @memberof SearchSpuListDto
     */
    noResultsTips: string;
    /**
     * 
     * @type {string}
     * @memberof SearchSpuListDto
     */
    notFirstSearchNoResult: string;
    /**
     * 
     * @type {string}
     * @memberof SearchSpuListDto
     */
    fallBackSpuListTitle: string;
    /**
     * 
     * @type {string}
     * @memberof SearchSpuListDto
     */
    noResultsTitle?: string;
    /**
     * 
     * @type {object}
     * @memberof SearchSpuListDto
     */
    smartMenu?: object;
    fallbackSpuList?: Array<SpuListItemDto>;
}

/**
 * Check if a given object implements the SearchSpuListDto interface.
 */
export function instanceOfSearchSpuListDto(value: object): boolean {
    if (!('total' in value)) return false;
    if (!('spuList' in value)) return false;
    if (!('algoAcmDto' in value)) return false;
    if (!('noResultsTips' in value)) return false;
    if (!('notFirstSearchNoResult' in value)) return false;
    if (!('fallBackSpuListTitle' in value)) return false;
    return true;
}

export function SearchSpuListDtoFromJSON(json: any): SearchSpuListDto {
    return SearchSpuListDtoFromJSONTyped(json, false);
}

export function SearchSpuListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSpuListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'spuList': ((json['spuList'] as Array<any>).map(SpuListItemDtoFromJSON)),
        'algoAcmDto': AlgoAcmDtoFromJSON(json['algoAcmDto']),
        'noResultsTips': json['noResultsTips'],
        'notFirstSearchNoResult': json['notFirstSearchNoResult'],
        'fallBackSpuListTitle': json['fallBackSpuListTitle'],
        'noResultsTitle': json['noResultsTitle'] == null ? undefined : json['noResultsTitle'],
        'smartMenu': json['smartMenu'] == null ? undefined : json['smartMenu'],
    };
}

export function SearchSpuListDtoToJSON(value?: SearchSpuListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'spuList': ((value['spuList'] as Array<any>).map(SpuListItemDtoToJSON)),
        'algoAcmDto': AlgoAcmDtoToJSON(value['algoAcmDto']),
        'noResultsTips': value['noResultsTips'],
        'notFirstSearchNoResult': value['notFirstSearchNoResult'],
        'fallBackSpuListTitle': value['fallBackSpuListTitle'],
        'noResultsTitle': value['noResultsTitle'],
        'smartMenu': value['smartMenu'],
    };
}

