/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchProductsRequestDto
 */
export interface SearchProductsRequestDto {
    /**
     * Search query string
     * @type {string}
     * @memberof SearchProductsRequestDto
     */
    query?: string;
    /**
     * Category ID or array of category IDs
     * @type {Array<number>}
     * @memberof SearchProductsRequestDto
     */
    categories?: Array<number>;
    /**
     * Array of brand IDs
     * @type {Array<number>}
     * @memberof SearchProductsRequestDto
     */
    brands?: Array<number>;
    /**
     * Array of model IDs
     * @type {Array<number>}
     * @memberof SearchProductsRequestDto
     */
    models?: Array<number>;
    /**
     * Array of genders
     * @type {Array<string>}
     * @memberof SearchProductsRequestDto
     */
    genders?: Array<SearchProductsRequestDtoGendersEnum>;
    /**
     * Minimum price
     * @type {number}
     * @memberof SearchProductsRequestDto
     */
    priceMin?: number;
    /**
     * Maximum price
     * @type {number}
     * @memberof SearchProductsRequestDto
     */
    priceMax?: number;
    /**
     * Minimum rating
     * @type {number}
     * @memberof SearchProductsRequestDto
     */
    ratingMin?: number;
    /**
     * Целевая валюта для конвертации цен
     * @type {string}
     * @memberof SearchProductsRequestDto
     */
    currency?: SearchProductsRequestDtoCurrencyEnum;
    /**
     * Include Custom's
     * @type {boolean}
     * @memberof SearchProductsRequestDto
     */
    includeCustom?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SearchProductsRequestDto
     */
    selectionId?: number;
    /**
     * Array of product selection IDs to exclude products from search results
     * @type {Array<number>}
     * @memberof SearchProductsRequestDto
     */
    excludeSelectionIds?: Array<number>;
    /**
     * Array of sources
     * @type {Array<string>}
     * @memberof SearchProductsRequestDto
     */
    sources?: Array<SearchProductsRequestDtoSourcesEnum>;
    /**
     * Limit results
     * @type {number}
     * @memberof SearchProductsRequestDto
     */
    limit?: number;
    /**
     * Last elemend id for pagination
     * @type {string}
     * @memberof SearchProductsRequestDto
     */
    cursor?: string;
    /**
     * Sorting method
     * @type {string}
     * @memberof SearchProductsRequestDto
     */
    sortBy?: SearchProductsRequestDtoSortByEnum;
}


/**
 * @export
 */
export const SearchProductsRequestDtoGendersEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type SearchProductsRequestDtoGendersEnum = typeof SearchProductsRequestDtoGendersEnum[keyof typeof SearchProductsRequestDtoGendersEnum];

/**
 * @export
 */
export const SearchProductsRequestDtoCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type SearchProductsRequestDtoCurrencyEnum = typeof SearchProductsRequestDtoCurrencyEnum[keyof typeof SearchProductsRequestDtoCurrencyEnum];

/**
 * @export
 */
export const SearchProductsRequestDtoSourcesEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type SearchProductsRequestDtoSourcesEnum = typeof SearchProductsRequestDtoSourcesEnum[keyof typeof SearchProductsRequestDtoSourcesEnum];

/**
 * @export
 */
export const SearchProductsRequestDtoSortByEnum = {
    Relevance: 'relevance',
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Popularity: 'popularity',
    Newest: 'newest'
} as const;
export type SearchProductsRequestDtoSortByEnum = typeof SearchProductsRequestDtoSortByEnum[keyof typeof SearchProductsRequestDtoSortByEnum];


/**
 * Check if a given object implements the SearchProductsRequestDto interface.
 */
export function instanceOfSearchProductsRequestDto(value: object): boolean {
    return true;
}

export function SearchProductsRequestDtoFromJSON(json: any): SearchProductsRequestDto {
    return SearchProductsRequestDtoFromJSONTyped(json, false);
}

export function SearchProductsRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchProductsRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'categories': json['categories'] == null ? undefined : json['categories'],
        'brands': json['brands'] == null ? undefined : json['brands'],
        'models': json['models'] == null ? undefined : json['models'],
        'genders': json['genders'] == null ? undefined : json['genders'],
        'priceMin': json['priceMin'] == null ? undefined : json['priceMin'],
        'priceMax': json['priceMax'] == null ? undefined : json['priceMax'],
        'ratingMin': json['ratingMin'] == null ? undefined : json['ratingMin'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'includeCustom': json['includeCustom'] == null ? undefined : json['includeCustom'],
        'selectionId': json['selectionId'] == null ? undefined : json['selectionId'],
        'excludeSelectionIds': json['excludeSelectionIds'] == null ? undefined : json['excludeSelectionIds'],
        'sources': json['sources'] == null ? undefined : json['sources'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'sortBy': json['sortBy'] == null ? undefined : json['sortBy'],
    };
}

export function SearchProductsRequestDtoToJSON(value?: SearchProductsRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
        'categories': value['categories'],
        'brands': value['brands'],
        'models': value['models'],
        'genders': value['genders'],
        'priceMin': value['priceMin'],
        'priceMax': value['priceMax'],
        'ratingMin': value['ratingMin'],
        'currency': value['currency'],
        'includeCustom': value['includeCustom'],
        'selectionId': value['selectionId'],
        'excludeSelectionIds': value['excludeSelectionIds'],
        'sources': value['sources'],
        'limit': value['limit'],
        'cursor': value['cursor'],
        'sortBy': value['sortBy'],
    };
}

