/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacetDto } from './FacetDto';
import {
    FacetDtoFromJSON,
    FacetDtoFromJSONTyped,
    FacetDtoToJSON,
} from './FacetDto';
import type { SearchSpuListDto } from './SearchSpuListDto';
import {
    SearchSpuListDtoFromJSON,
    SearchSpuListDtoFromJSONTyped,
    SearchSpuListDtoToJSON,
} from './SearchSpuListDto';
import type { SortTabInfoDto } from './SortTabInfoDto';
import {
    SortTabInfoDtoFromJSON,
    SortTabInfoDtoFromJSONTyped,
    SortTabInfoDtoToJSON,
} from './SortTabInfoDto';

/**
 * 
 * @export
 * @interface SearchResponseDto
 */
export interface SearchResponseDto {
    /**
     * 
     * @type {SearchSpuListDto}
     * @memberof SearchResponseDto
     */
    searchSpuList: SearchSpuListDto;
    /**
     * 
     * @type {number}
     * @memberof SearchResponseDto
     */
    aggTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchResponseDto
     */
    aggTotalText?: string;
    /**
     * 
     * @type {SortTabInfoDto}
     * @memberof SearchResponseDto
     */
    sortTabInfo?: SortTabInfoDto;
    /**
     * 
     * @type {Array<FacetDto>}
     * @memberof SearchResponseDto
     */
    facets?: Array<FacetDto>;
}

/**
 * Check if a given object implements the SearchResponseDto interface.
 */
export function instanceOfSearchResponseDto(value: object): boolean {
    if (!('searchSpuList' in value)) return false;
    return true;
}

export function SearchResponseDtoFromJSON(json: any): SearchResponseDto {
    return SearchResponseDtoFromJSONTyped(json, false);
}

export function SearchResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'searchSpuList': SearchSpuListDtoFromJSON(json['searchSpuList']),
        'aggTotal': json['aggTotal'] == null ? undefined : json['aggTotal'],
        'aggTotalText': json['aggTotalText'] == null ? undefined : json['aggTotalText'],
        'sortTabInfo': json['sortTabInfo'] == null ? undefined : SortTabInfoDtoFromJSON(json['sortTabInfo']),
        'facets': json['facets'] == null ? undefined : ((json['facets'] as Array<any>).map(FacetDtoFromJSON)),
    };
}

export function SearchResponseDtoToJSON(value?: SearchResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'searchSpuList': SearchSpuListDtoToJSON(value['searchSpuList']),
        'aggTotal': value['aggTotal'],
        'aggTotalText': value['aggTotalText'],
        'sortTabInfo': SortTabInfoDtoToJSON(value['sortTabInfo']),
        'facets': value['facets'] == null ? undefined : ((value['facets'] as Array<any>).map(FacetDtoToJSON)),
    };
}

