/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareInfoDto
 */
export interface ShareInfoDto {
    /**
     * 
     * @type {string}
     * @memberof ShareInfoDto
     */
    shareImageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ShareInfoDto
     */
    shareContent: string;
    /**
     * 
     * @type {string}
     * @memberof ShareInfoDto
     */
    shareTitle: string;
    /**
     * 
     * @type {string}
     * @memberof ShareInfoDto
     */
    shareUrl: string;
}

/**
 * Check if a given object implements the ShareInfoDto interface.
 */
export function instanceOfShareInfoDto(value: object): boolean {
    if (!('shareImageUrl' in value)) return false;
    if (!('shareContent' in value)) return false;
    if (!('shareTitle' in value)) return false;
    if (!('shareUrl' in value)) return false;
    return true;
}

export function ShareInfoDtoFromJSON(json: any): ShareInfoDto {
    return ShareInfoDtoFromJSONTyped(json, false);
}

export function ShareInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'shareImageUrl': json['shareImageUrl'],
        'shareContent': json['shareContent'],
        'shareTitle': json['shareTitle'],
        'shareUrl': json['shareUrl'],
    };
}

export function ShareInfoDtoToJSON(value?: ShareInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'shareImageUrl': value['shareImageUrl'],
        'shareContent': value['shareContent'],
        'shareTitle': value['shareTitle'],
        'shareUrl': value['shareUrl'],
    };
}

