/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingMethodDto
 */
export interface ShippingMethodDto {
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDto
     */
    content: string;
}

/**
 * Check if a given object implements the ShippingMethodDto interface.
 */
export function instanceOfShippingMethodDto(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('content' in value)) return false;
    return true;
}

export function ShippingMethodDtoFromJSON(json: any): ShippingMethodDto {
    return ShippingMethodDtoFromJSONTyped(json, false);
}

export function ShippingMethodDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingMethodDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function ShippingMethodDtoToJSON(value?: ShippingMethodDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

