/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendSizeDto } from './RecommendSizeDto';
import {
    RecommendSizeDtoFromJSON,
    RecommendSizeDtoFromJSONTyped,
    RecommendSizeDtoToJSON,
} from './RecommendSizeDto';
import type { SizeDto } from './SizeDto';
import {
    SizeDtoFromJSON,
    SizeDtoFromJSONTyped,
    SizeDtoToJSON,
} from './SizeDto';

/**
 * 
 * @export
 * @interface SizeTableResponseDto
 */
export interface SizeTableResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof SizeTableResponseDto
     */
    conversionAsianToUSText: boolean;
    /**
     * 
     * @type {RecommendSizeDto}
     * @memberof SizeTableResponseDto
     */
    recommendSize: RecommendSizeDto;
    /**
     * 
     * @type {string}
     * @memberof SizeTableResponseDto
     */
    commoditySizeTipsKey: string;
    /**
     * 
     * @type {string}
     * @memberof SizeTableResponseDto
     */
    deviationCodePrompt: string;
    /**
     * 
     * @type {SizeDto}
     * @memberof SizeTableResponseDto
     */
    size: SizeDto;
    /**
     * 
     * @type {string}
     * @memberof SizeTableResponseDto
     */
    tableStyle: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof SizeTableResponseDto
     */
    sizeImageList: Array<object>;
}

/**
 * Check if a given object implements the SizeTableResponseDto interface.
 */
export function instanceOfSizeTableResponseDto(value: object): boolean {
    if (!('conversionAsianToUSText' in value)) return false;
    if (!('recommendSize' in value)) return false;
    if (!('commoditySizeTipsKey' in value)) return false;
    if (!('deviationCodePrompt' in value)) return false;
    if (!('size' in value)) return false;
    if (!('tableStyle' in value)) return false;
    if (!('sizeImageList' in value)) return false;
    return true;
}

export function SizeTableResponseDtoFromJSON(json: any): SizeTableResponseDto {
    return SizeTableResponseDtoFromJSONTyped(json, false);
}

export function SizeTableResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeTableResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'conversionAsianToUSText': json['conversionAsianToUSText'],
        'recommendSize': RecommendSizeDtoFromJSON(json['recommendSize']),
        'commoditySizeTipsKey': json['commoditySizeTipsKey'],
        'deviationCodePrompt': json['deviationCodePrompt'],
        'size': SizeDtoFromJSON(json['size']),
        'tableStyle': json['tableStyle'],
        'sizeImageList': json['sizeImageList'],
    };
}

export function SizeTableResponseDtoToJSON(value?: SizeTableResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'conversionAsianToUSText': value['conversionAsianToUSText'],
        'recommendSize': RecommendSizeDtoToJSON(value['recommendSize']),
        'commoditySizeTipsKey': value['commoditySizeTipsKey'],
        'deviationCodePrompt': value['deviationCodePrompt'],
        'size': SizeDtoToJSON(value['size']),
        'tableStyle': value['tableStyle'],
        'sizeImageList': value['sizeImageList'],
    };
}

