/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SizeKeyListDto } from './SizeKeyListDto';
import {
    SizeKeyListDtoFromJSON,
    SizeKeyListDtoFromJSONTyped,
    SizeKeyListDtoToJSON,
} from './SizeKeyListDto';
import type { SizeParameterListDto } from './SizeParameterListDto';
import {
    SizeParameterListDtoFromJSON,
    SizeParameterListDtoFromJSONTyped,
    SizeParameterListDtoToJSON,
} from './SizeParameterListDto';

/**
 * 
 * @export
 * @interface SizeListDto
 */
export interface SizeListDto {
    /**
     * 
     * @type {Array<SizeKeyListDto>}
     * @memberof SizeListDto
     */
    sizeKeyList: Array<SizeKeyListDto>;
    /**
     * 
     * @type {Array<SizeParameterListDto>}
     * @memberof SizeListDto
     */
    sizeParameterList: Array<SizeParameterListDto>;
    /**
     * 
     * @type {string}
     * @memberof SizeListDto
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof SizeListDto
     */
    selected?: boolean;
}

/**
 * Check if a given object implements the SizeListDto interface.
 */
export function instanceOfSizeListDto(value: object): boolean {
    if (!('sizeKeyList' in value)) return false;
    if (!('sizeParameterList' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function SizeListDtoFromJSON(json: any): SizeListDto {
    return SizeListDtoFromJSONTyped(json, false);
}

export function SizeListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeKeyList': ((json['sizeKeyList'] as Array<any>).map(SizeKeyListDtoFromJSON)),
        'sizeParameterList': ((json['sizeParameterList'] as Array<any>).map(SizeParameterListDtoFromJSON)),
        'title': json['title'],
        'selected': json['selected'] == null ? undefined : json['selected'],
    };
}

export function SizeListDtoToJSON(value?: SizeListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sizeKeyList': ((value['sizeKeyList'] as Array<any>).map(SizeKeyListDtoToJSON)),
        'sizeParameterList': ((value['sizeParameterList'] as Array<any>).map(SizeParameterListDtoToJSON)),
        'title': value['title'],
        'selected': value['selected'],
    };
}

