/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SizeKeyListDto
 */
export interface SizeKeyListDto {
    /**
     * 
     * @type {string}
     * @memberof SizeKeyListDto
     */
    sizeKey: string;
    /**
     * 
     * @type {string}
     * @memberof SizeKeyListDto
     */
    sizeValue: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SizeKeyListDto
     */
    sizeValueList: Array<string>;
}

/**
 * Check if a given object implements the SizeKeyListDto interface.
 */
export function instanceOfSizeKeyListDto(value: object): boolean {
    if (!('sizeKey' in value)) return false;
    if (!('sizeValue' in value)) return false;
    if (!('sizeValueList' in value)) return false;
    return true;
}

export function SizeKeyListDtoFromJSON(json: any): SizeKeyListDto {
    return SizeKeyListDtoFromJSONTyped(json, false);
}

export function SizeKeyListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeKeyListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeKey': json['sizeKey'],
        'sizeValue': json['sizeValue'],
        'sizeValueList': json['sizeValueList'],
    };
}

export function SizeKeyListDtoToJSON(value?: SizeKeyListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sizeKey': value['sizeKey'],
        'sizeValue': value['sizeValue'],
        'sizeValueList': value['sizeValueList'],
    };
}

