/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SizeParameterListDto
 */
export interface SizeParameterListDto {
    /**
     * 
     * @type {string}
     * @memberof SizeParameterListDto
     */
    sizeKey: string;
    /**
     * 
     * @type {string}
     * @memberof SizeParameterListDto
     */
    sizeValue: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SizeParameterListDto
     */
    sizeValueList: Array<string>;
}

/**
 * Check if a given object implements the SizeParameterListDto interface.
 */
export function instanceOfSizeParameterListDto(value: object): boolean {
    if (!('sizeKey' in value)) return false;
    if (!('sizeValue' in value)) return false;
    if (!('sizeValueList' in value)) return false;
    return true;
}

export function SizeParameterListDtoFromJSON(json: any): SizeParameterListDto {
    return SizeParameterListDtoFromJSONTyped(json, false);
}

export function SizeParameterListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeParameterListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeKey': json['sizeKey'],
        'sizeValue': json['sizeValue'],
        'sizeValueList': json['sizeValueList'],
    };
}

export function SizeParameterListDtoToJSON(value?: SizeParameterListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sizeKey': value['sizeKey'],
        'sizeValue': value['sizeValue'],
        'sizeValueList': value['sizeValueList'],
    };
}

