/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SizeListDto } from './SizeListDto';
import {
    SizeListDtoFromJSON,
    SizeListDtoFromJSONTyped,
    SizeListDtoToJSON,
} from './SizeListDto';

/**
 * 
 * @export
 * @interface SizeDto
 */
export interface SizeDto {
    /**
     * 
     * @type {Array<SizeListDto>}
     * @memberof SizeDto
     */
    sizeList: Array<SizeListDto>;
    /**
     * 
     * @type {boolean}
     * @memberof SizeDto
     */
    sizeConversionAsianToUS: boolean;
}

/**
 * Check if a given object implements the SizeDto interface.
 */
export function instanceOfSizeDto(value: object): boolean {
    if (!('sizeList' in value)) return false;
    if (!('sizeConversionAsianToUS' in value)) return false;
    return true;
}

export function SizeDtoFromJSON(json: any): SizeDto {
    return SizeDtoFromJSONTyped(json, false);
}

export function SizeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeList': ((json['sizeList'] as Array<any>).map(SizeListDtoFromJSON)),
        'sizeConversionAsianToUS': json['sizeConversionAsianToUS'],
    };
}

export function SizeDtoToJSON(value?: SizeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sizeList': ((value['sizeList'] as Array<any>).map(SizeListDtoToJSON)),
        'sizeConversionAsianToUS': value['sizeConversionAsianToUS'],
    };
}

