/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CouponInfoDto } from './CouponInfoDto';
import {
    CouponInfoDtoFromJSON,
    CouponInfoDtoFromJSONTyped,
    CouponInfoDtoToJSON,
} from './CouponInfoDto';
import type { PropertyDto } from './PropertyDto';
import {
    PropertyDtoFromJSON,
    PropertyDtoFromJSONTyped,
    PropertyDtoToJSON,
} from './PropertyDto';
import type { SkuSpeedInfoDto } from './SkuSpeedInfoDto';
import {
    SkuSpeedInfoDtoFromJSON,
    SkuSpeedInfoDtoFromJSONTyped,
    SkuSpeedInfoDtoToJSON,
} from './SkuSpeedInfoDto';
import type { SpeedPriceDto } from './SpeedPriceDto';
import {
    SpeedPriceDtoFromJSON,
    SpeedPriceDtoFromJSONTyped,
    SpeedPriceDtoToJSON,
} from './SpeedPriceDto';

/**
 * 
 * @export
 * @interface SkusDto
 */
export interface SkusDto {
    /**
     * 
     * @type {string}
     * @memberof SkusDto
     */
    skuTitle: string;
    /**
     * 
     * @type {CouponInfoDto}
     * @memberof SkusDto
     */
    couponInfo: CouponInfoDto;
    /**
     * 
     * @type {number}
     * @memberof SkusDto
     */
    spuId: number;
    /**
     * 
     * @type {number}
     * @memberof SkusDto
     */
    skuId: number;
    /**
     * 
     * @type {number}
     * @memberof SkusDto
     */
    authPrice: number;
    /**
     * 
     * @type {Array<PropertyDto>}
     * @memberof SkusDto
     */
    properties: Array<PropertyDto>;
    /**
     * 
     * @type {number}
     * @memberof SkusDto
     */
    status: number;
    /**
     * 
     * @type {Array<SkuSpeedInfoDto>}
     * @memberof SkusDto
     */
    skuSpeedInfo?: Array<SkuSpeedInfoDto>;
    /**
     * 
     * @type {SpeedPriceDto}
     * @memberof SkusDto
     */
    minPrice?: SpeedPriceDto;
    /**
     * 
     * @type {SpeedPriceDto}
     * @memberof SkusDto
     */
    customsPrice?: SpeedPriceDto;
}

/**
 * Check if a given object implements the SkusDto interface.
 */
export function instanceOfSkusDto(value: object): boolean {
    if (!('skuTitle' in value)) return false;
    if (!('couponInfo' in value)) return false;
    if (!('spuId' in value)) return false;
    if (!('skuId' in value)) return false;
    if (!('authPrice' in value)) return false;
    if (!('properties' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function SkusDtoFromJSON(json: any): SkusDto {
    return SkusDtoFromJSONTyped(json, false);
}

export function SkusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'skuTitle': json['skuTitle'],
        'couponInfo': CouponInfoDtoFromJSON(json['couponInfo']),
        'spuId': json['spuId'],
        'skuId': json['skuId'],
        'authPrice': json['authPrice'],
        'properties': ((json['properties'] as Array<any>).map(PropertyDtoFromJSON)),
        'status': json['status'],
        'skuSpeedInfo': json['skuSpeedInfo'] == null ? undefined : ((json['skuSpeedInfo'] as Array<any>).map(SkuSpeedInfoDtoFromJSON)),
        'minPrice': json['minPrice'] == null ? undefined : SpeedPriceDtoFromJSON(json['minPrice']),
        'customsPrice': json['customsPrice'] == null ? undefined : SpeedPriceDtoFromJSON(json['customsPrice']),
    };
}

export function SkusDtoToJSON(value?: SkusDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'skuTitle': value['skuTitle'],
        'couponInfo': CouponInfoDtoToJSON(value['couponInfo']),
        'spuId': value['spuId'],
        'skuId': value['skuId'],
        'authPrice': value['authPrice'],
        'properties': ((value['properties'] as Array<any>).map(PropertyDtoToJSON)),
        'status': value['status'],
        'skuSpeedInfo': value['skuSpeedInfo'] == null ? undefined : ((value['skuSpeedInfo'] as Array<any>).map(SkuSpeedInfoDtoToJSON)),
        'minPrice': SpeedPriceDtoToJSON(value['minPrice']),
        'customsPrice': SpeedPriceDtoToJSON(value['customsPrice']),
    };
}

