/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpeedPriceDto } from './SpeedPriceDto';
import {
    SpeedPriceDtoFromJSON,
    SpeedPriceDtoFromJSONTyped,
    SpeedPriceDtoToJSON,
} from './SpeedPriceDto';

/**
 * 
 * @export
 * @interface SkuSpeedInfoDto
 */
export interface SkuSpeedInfoDto {
    /**
     * 
     * @type {number}
     * @memberof SkuSpeedInfoDto
     */
    minDay: number;
    /**
     * 
     * @type {string}
     * @memberof SkuSpeedInfoDto
     */
    speedInfoTip: string;
    /**
     * 
     * @type {string}
     * @memberof SkuSpeedInfoDto
     */
    saleInventoryNo: string;
    /**
     * 
     * @type {number}
     * @memberof SkuSpeedInfoDto
     */
    maxDay: number;
    /**
     * 
     * @type {SpeedPriceDto}
     * @memberof SkuSpeedInfoDto
     */
    speedPrice: SpeedPriceDto;
    /**
     * 
     * @type {string}
     * @memberof SkuSpeedInfoDto
     */
    skuDeliveryDesc: string;
}

/**
 * Check if a given object implements the SkuSpeedInfoDto interface.
 */
export function instanceOfSkuSpeedInfoDto(value: object): boolean {
    if (!('minDay' in value)) return false;
    if (!('speedInfoTip' in value)) return false;
    if (!('saleInventoryNo' in value)) return false;
    if (!('maxDay' in value)) return false;
    if (!('speedPrice' in value)) return false;
    if (!('skuDeliveryDesc' in value)) return false;
    return true;
}

export function SkuSpeedInfoDtoFromJSON(json: any): SkuSpeedInfoDto {
    return SkuSpeedInfoDtoFromJSONTyped(json, false);
}

export function SkuSpeedInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkuSpeedInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'minDay': json['minDay'],
        'speedInfoTip': json['speedInfoTip'],
        'saleInventoryNo': json['saleInventoryNo'],
        'maxDay': json['maxDay'],
        'speedPrice': SpeedPriceDtoFromJSON(json['speedPrice']),
        'skuDeliveryDesc': json['skuDeliveryDesc'],
    };
}

export function SkuSpeedInfoDtoToJSON(value?: SkuSpeedInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'minDay': value['minDay'],
        'speedInfoTip': value['speedInfoTip'],
        'saleInventoryNo': value['saleInventoryNo'],
        'maxDay': value['maxDay'],
        'speedPrice': SpeedPriceDtoToJSON(value['speedPrice']),
        'skuDeliveryDesc': value['skuDeliveryDesc'],
    };
}

