/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SortModeDto
 */
export interface SortModeDto {
    /**
     * 
     * @type {string}
     * @memberof SortModeDto
     */
    tabText?: string;
    /**
     * 
     * @type {number}
     * @memberof SortModeDto
     */
    sortMode?: number;
}

/**
 * Check if a given object implements the SortModeDto interface.
 */
export function instanceOfSortModeDto(value: object): boolean {
    return true;
}

export function SortModeDtoFromJSON(json: any): SortModeDto {
    return SortModeDtoFromJSONTyped(json, false);
}

export function SortModeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortModeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tabText': json['tabText'] == null ? undefined : json['tabText'],
        'sortMode': json['sortMode'] == null ? undefined : json['sortMode'],
    };
}

export function SortModeDtoToJSON(value?: SortModeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tabText': value['tabText'],
        'sortMode': value['sortMode'],
    };
}

