/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TabSortMappingDto } from './TabSortMappingDto';
import {
    TabSortMappingDtoFromJSON,
    TabSortMappingDtoFromJSONTyped,
    TabSortMappingDtoToJSON,
} from './TabSortMappingDto';

/**
 * 
 * @export
 * @interface SortTabInfoDto
 */
export interface SortTabInfoDto {
    /**
     * 
     * @type {Array<TabSortMappingDto>}
     * @memberof SortTabInfoDto
     */
    tabSortMappings: Array<TabSortMappingDto>;
}

/**
 * Check if a given object implements the SortTabInfoDto interface.
 */
export function instanceOfSortTabInfoDto(value: object): boolean {
    if (!('tabSortMappings' in value)) return false;
    return true;
}

export function SortTabInfoDtoFromJSON(json: any): SortTabInfoDto {
    return SortTabInfoDtoFromJSONTyped(json, false);
}

export function SortTabInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortTabInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'tabSortMappings': ((json['tabSortMappings'] as Array<any>).map(TabSortMappingDtoFromJSON)),
    };
}

export function SortTabInfoDtoToJSON(value?: SortTabInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tabSortMappings': ((value['tabSortMappings'] as Array<any>).map(TabSortMappingDtoToJSON)),
    };
}

