/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlgoAcmItemDto } from './AlgoAcmItemDto';
import {
    AlgoAcmItemDtoFromJSON,
    AlgoAcmItemDtoFromJSONTyped,
    AlgoAcmItemDtoToJSON,
} from './AlgoAcmItemDto';
import type { LabelModelDto } from './LabelModelDto';
import {
    LabelModelDtoFromJSON,
    LabelModelDtoFromJSONTyped,
    LabelModelDtoToJSON,
} from './LabelModelDto';
import type { MinSpuPriceDto } from './MinSpuPriceDto';
import {
    MinSpuPriceDtoFromJSON,
    MinSpuPriceDtoFromJSONTyped,
    MinSpuPriceDtoToJSON,
} from './MinSpuPriceDto';

/**
 * 
 * @export
 * @interface SpuListItemDto
 */
export interface SpuListItemDto {
    /**
     * 
     * @type {MinSpuPriceDto}
     * @memberof SpuListItemDto
     */
    minSpuPrice: MinSpuPriceDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpuListItemDto
     */
    rankingTags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    language: string;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    imageCutSize: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    favoriteStatus: number;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    logoUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    articleNumber: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof SpuListItemDto
     */
    tradingRoles: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    brandId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    spuId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    level2CategoryId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    sellDate: number;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    region: string;
    /**
     * 
     * @type {AlgoAcmItemDto}
     * @memberof SpuListItemDto
     */
    algoAcmItem: AlgoAcmItemDto;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    globalSpuId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    categoryId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    level1CategoryId: number;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    saleTag?: string;
    /**
     * 
     * @type {string}
     * @memberof SpuListItemDto
     */
    googleProductCategory?: string;
    /**
     * 
     * @type {number}
     * @memberof SpuListItemDto
     */
    contentCategory?: number;
    /**
     * 
     * @type {LabelModelDto}
     * @memberof SpuListItemDto
     */
    labelModel?: LabelModelDto;
}

/**
 * Check if a given object implements the SpuListItemDto interface.
 */
export function instanceOfSpuListItemDto(value: object): boolean {
    if (!('minSpuPrice' in value)) return false;
    if (!('rankingTags' in value)) return false;
    if (!('language' in value)) return false;
    if (!('imageCutSize' in value)) return false;
    if (!('favoriteStatus' in value)) return false;
    if (!('title' in value)) return false;
    if (!('logoUrl' in value)) return false;
    if (!('url' in value)) return false;
    if (!('articleNumber' in value)) return false;
    if (!('tradingRoles' in value)) return false;
    if (!('brandId' in value)) return false;
    if (!('spuId' in value)) return false;
    if (!('level2CategoryId' in value)) return false;
    if (!('sellDate' in value)) return false;
    if (!('region' in value)) return false;
    if (!('algoAcmItem' in value)) return false;
    if (!('globalSpuId' in value)) return false;
    if (!('categoryId' in value)) return false;
    if (!('level1CategoryId' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function SpuListItemDtoFromJSON(json: any): SpuListItemDto {
    return SpuListItemDtoFromJSONTyped(json, false);
}

export function SpuListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpuListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'minSpuPrice': MinSpuPriceDtoFromJSON(json['minSpuPrice']),
        'rankingTags': json['rankingTags'],
        'language': json['language'],
        'imageCutSize': json['imageCutSize'],
        'favoriteStatus': json['favoriteStatus'],
        'title': json['title'],
        'logoUrl': json['logoUrl'],
        'url': json['url'],
        'articleNumber': json['articleNumber'],
        'tradingRoles': json['tradingRoles'],
        'brandId': json['brandId'],
        'spuId': json['spuId'],
        'level2CategoryId': json['level2CategoryId'],
        'sellDate': json['sellDate'],
        'region': json['region'],
        'algoAcmItem': AlgoAcmItemDtoFromJSON(json['algoAcmItem']),
        'globalSpuId': json['globalSpuId'],
        'categoryId': json['categoryId'],
        'level1CategoryId': json['level1CategoryId'],
        'status': json['status'],
        'saleTag': json['saleTag'] == null ? undefined : json['saleTag'],
        'googleProductCategory': json['googleProductCategory'] == null ? undefined : json['googleProductCategory'],
        'contentCategory': json['contentCategory'] == null ? undefined : json['contentCategory'],
        'labelModel': json['labelModel'] == null ? undefined : LabelModelDtoFromJSON(json['labelModel']),
    };
}

export function SpuListItemDtoToJSON(value?: SpuListItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'minSpuPrice': MinSpuPriceDtoToJSON(value['minSpuPrice']),
        'rankingTags': value['rankingTags'],
        'language': value['language'],
        'imageCutSize': value['imageCutSize'],
        'favoriteStatus': value['favoriteStatus'],
        'title': value['title'],
        'logoUrl': value['logoUrl'],
        'url': value['url'],
        'articleNumber': value['articleNumber'],
        'tradingRoles': value['tradingRoles'],
        'brandId': value['brandId'],
        'spuId': value['spuId'],
        'level2CategoryId': value['level2CategoryId'],
        'sellDate': value['sellDate'],
        'region': value['region'],
        'algoAcmItem': AlgoAcmItemDtoToJSON(value['algoAcmItem']),
        'globalSpuId': value['globalSpuId'],
        'categoryId': value['categoryId'],
        'level1CategoryId': value['level1CategoryId'],
        'status': value['status'],
        'saleTag': value['saleTag'],
        'googleProductCategory': value['googleProductCategory'],
        'contentCategory': value['contentCategory'],
        'labelModel': LabelModelDtoToJSON(value['labelModel']),
    };
}

