/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortModeDto } from './SortModeDto';
import {
    SortModeDtoFromJSON,
    SortModeDtoFromJSONTyped,
    SortModeDtoToJSON,
} from './SortModeDto';

/**
 * 
 * @export
 * @interface TabSortMappingDto
 */
export interface TabSortMappingDto {
    /**
     * 
     * @type {number}
     * @memberof TabSortMappingDto
     */
    sortType: number;
    /**
     * 
     * @type {string}
     * @memberof TabSortMappingDto
     */
    tabText: string;
    /**
     * 
     * @type {Array<SortModeDto>}
     * @memberof TabSortMappingDto
     */
    sortModes: Array<SortModeDto>;
}

/**
 * Check if a given object implements the TabSortMappingDto interface.
 */
export function instanceOfTabSortMappingDto(value: object): boolean {
    if (!('sortType' in value)) return false;
    if (!('tabText' in value)) return false;
    if (!('sortModes' in value)) return false;
    return true;
}

export function TabSortMappingDtoFromJSON(json: any): TabSortMappingDto {
    return TabSortMappingDtoFromJSONTyped(json, false);
}

export function TabSortMappingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TabSortMappingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sortType': json['sortType'],
        'tabText': json['tabText'],
        'sortModes': ((json['sortModes'] as Array<any>).map(SortModeDtoFromJSON)),
    };
}

export function TabSortMappingDtoToJSON(value?: TabSortMappingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sortType': value['sortType'],
        'tabText': value['tabText'],
        'sortModes': ((value['sortModes'] as Array<any>).map(SortModeDtoToJSON)),
    };
}

