/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductSelectionDto
 */
export interface UpdateProductSelectionDto {
    /**
     * Название подборки (макс. 60 символов)
     * @type {string}
     * @memberof UpdateProductSelectionDto
     */
    name?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateProductSelectionDto
     */
    productIds?: Array<number>;
}

/**
 * Check if a given object implements the UpdateProductSelectionDto interface.
 */
export function instanceOfUpdateProductSelectionDto(value: object): boolean {
    return true;
}

export function UpdateProductSelectionDtoFromJSON(json: any): UpdateProductSelectionDto {
    return UpdateProductSelectionDtoFromJSONTyped(json, false);
}

export function UpdateProductSelectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductSelectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'productIds': json['productIds'] == null ? undefined : json['productIds'],
    };
}

export function UpdateProductSelectionDtoToJSON(value?: UpdateProductSelectionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'productIds': value['productIds'],
    };
}

