/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrandsResponseWithPaginationDto,
} from '../models/index';
import {
    BrandsResponseWithPaginationDtoFromJSON,
    BrandsResponseWithPaginationDtoToJSON,
} from '../models/index';

export interface BrandControllerGetBrandsRequest {
    id?: number;
    ids?: Array<number>;
    query?: string;
    limit?: number;
    cursor?: number;
    hideEmpty?: boolean;
    withCount?: boolean;
}

/**
 * 
 */
export class BrandApi extends runtime.BaseAPI {

    /**
     * Получение брендов по фильтру
     */
    async brandControllerGetBrandsRaw(requestParameters: BrandControllerGetBrandsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandsResponseWithPaginationDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['hideEmpty'] != null) {
            queryParameters['hideEmpty'] = requestParameters['hideEmpty'];
        }

        if (requestParameters['withCount'] != null) {
            queryParameters['withCount'] = requestParameters['withCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/brand`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandsResponseWithPaginationDtoFromJSON(jsonValue));
    }

    /**
     * Получение брендов по фильтру
     */
    async brandControllerGetBrands(requestParameters: BrandControllerGetBrandsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandsResponseWithPaginationDto> {
        const response = await this.brandControllerGetBrandsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
