/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoriesResponseWithPaginationDto,
  CategoryDto,
} from '../models/index';
import {
    CategoriesResponseWithPaginationDtoFromJSON,
    CategoriesResponseWithPaginationDtoToJSON,
    CategoryDtoFromJSON,
    CategoryDtoToJSON,
} from '../models/index';

export interface CategoryControllerGetCategoriesRequest {
    id?: number;
    ids?: Array<number>;
    query?: string;
    limit?: number;
    cursor?: number;
}

export interface CategoryControllerGetCategoriesTreeRequest {
    hideEmpty?: boolean;
    withCount?: boolean;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     * Получение списка категорий по фильтрам
     */
    async categoryControllerGetCategoriesRaw(requestParameters: CategoryControllerGetCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoriesResponseWithPaginationDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/category`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriesResponseWithPaginationDtoFromJSON(jsonValue));
    }

    /**
     * Получение списка категорий по фильтрам
     */
    async categoryControllerGetCategories(requestParameters: CategoryControllerGetCategoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoriesResponseWithPaginationDto> {
        const response = await this.categoryControllerGetCategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение всех категорий
     */
    async categoryControllerGetCategoriesTreeRaw(requestParameters: CategoryControllerGetCategoriesTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryDto>>> {
        const queryParameters: any = {};

        if (requestParameters['hideEmpty'] != null) {
            queryParameters['hideEmpty'] = requestParameters['hideEmpty'];
        }

        if (requestParameters['withCount'] != null) {
            queryParameters['withCount'] = requestParameters['withCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/category/tree`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryDtoFromJSON));
    }

    /**
     * Получение всех категорий
     */
    async categoryControllerGetCategoriesTree(requestParameters: CategoryControllerGetCategoriesTreeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryDto>> {
        const response = await this.categoryControllerGetCategoriesTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
