/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsResponseWithPaginationDto,
} from '../models/index';
import {
    ModelsResponseWithPaginationDtoFromJSON,
    ModelsResponseWithPaginationDtoToJSON,
} from '../models/index';

export interface ModelControllerGetModelsRequest {
    id?: number;
    ids?: Array<number>;
    query?: string;
    limit?: number;
    cursor?: number;
}

/**
 * 
 */
export class ModelApi extends runtime.BaseAPI {

    /**
     * Получение моеделей по фильтру
     */
    async modelControllerGetModelsRaw(requestParameters: ModelControllerGetModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsResponseWithPaginationDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/model`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsResponseWithPaginationDtoFromJSON(jsonValue));
    }

    /**
     * Получение моеделей по фильтру
     */
    async modelControllerGetModels(requestParameters: ModelControllerGetModelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsResponseWithPaginationDto> {
        const response = await this.modelControllerGetModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
