/* tslint:disable */
/* eslint-disable */
/**
 * Poizon API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/poizon-ru/api-json)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrandListResponseDto,
  CategoryFiltersResponseDto,
  CategoryTreeResponseDto,
  ProductInfoResponseDto,
  ReviewListResponseDto,
  SearchResponseDto,
  SizeTableResponseDto,
} from '../models/index';
import {
    BrandListResponseDtoFromJSON,
    BrandListResponseDtoToJSON,
    CategoryFiltersResponseDtoFromJSON,
    CategoryFiltersResponseDtoToJSON,
    CategoryTreeResponseDtoFromJSON,
    CategoryTreeResponseDtoToJSON,
    ProductInfoResponseDtoFromJSON,
    ProductInfoResponseDtoToJSON,
    ReviewListResponseDtoFromJSON,
    ReviewListResponseDtoToJSON,
    SearchResponseDtoFromJSON,
    SearchResponseDtoToJSON,
    SizeTableResponseDtoFromJSON,
    SizeTableResponseDtoToJSON,
} from '../models/index';

export interface PoizonApiControllerGetCategoryFiltersRequest {
    categoryId: string;
}

export interface PoizonApiControllerGetProductInfoRequest {
    spuId: number;
}

export interface PoizonApiControllerGetReviewsRequest {
    spuId: number;
    page?: number;
}

export interface PoizonApiControllerGetSizeTableRequest {
    spuId: number;
}

export interface PoizonApiControllerSearchRequest {
    page?: number;
    pageSize?: number;
    sortType?: PoizonApiControllerSearchSortTypeEnum;
    sortMode?: PoizonApiControllerSearchSortModeEnum;
    brandIds?: Array<number>;
    categoryIds?: Array<string>;
    seriesIds?: Array<string>;
    fitIds?: Array<number>;
    colors?: Array<string>;
    sizes?: Array<string>;
    priceMin?: number;
    priceMax?: number;
    keyword?: string;
}

export interface PoizonApiControllerSearchByBrandIdRequest {
    brandId: number;
    page?: number;
    pageSize?: number;
    sortType?: PoizonApiControllerSearchByBrandIdSortTypeEnum;
    sortMode?: PoizonApiControllerSearchByBrandIdSortModeEnum;
    categoryIds?: Array<string>;
    seriesIds?: Array<string>;
    fitIds?: Array<number>;
    colors?: Array<string>;
    sizes?: Array<string>;
    priceMin?: number;
    priceMax?: number;
}

export interface PoizonApiControllerSearchByCategoryRequest {
    categoryId: string;
    page?: number;
    pageSize?: number;
    sortType?: PoizonApiControllerSearchByCategorySortTypeEnum;
    sortMode?: PoizonApiControllerSearchByCategorySortModeEnum;
    brandIds?: Array<number>;
    categoryIds?: Array<string>;
    seriesIds?: Array<string>;
    fitIds?: Array<number>;
    colors?: Array<string>;
    sizes?: Array<string>;
    priceMin?: number;
    priceMax?: number;
}

/**
 * 
 */
export class PoizonApiApi extends runtime.BaseAPI {

    /**
     * Получение списка брендов
     */
    async poizonApiControllerGetBrandListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandListResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/brand-list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandListResponseDtoFromJSON(jsonValue));
    }

    /**
     * Получение списка брендов
     */
    async poizonApiControllerGetBrandList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandListResponseDto> {
        const response = await this.poizonApiControllerGetBrandListRaw(initOverrides);
        return await response.value();
    }

    /**
     * Фасеты для категории L1 или L3 со счётчиками товаров. Именно здесь лежат реальные значения для query-параметров brandIds, seriesIds, colors, sizes и fitIds.
     * Доступные фильтры категории
     */
    async poizonApiControllerGetCategoryFiltersRaw(requestParameters: PoizonApiControllerGetCategoryFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryFiltersResponseDto>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling poizonApiControllerGetCategoryFilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/category-filters/{categoryId}`.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryFiltersResponseDtoFromJSON(jsonValue));
    }

    /**
     * Фасеты для категории L1 или L3 со счётчиками товаров. Именно здесь лежат реальные значения для query-параметров brandIds, seriesIds, colors, sizes и fitIds.
     * Доступные фильтры категории
     */
    async poizonApiControllerGetCategoryFilters(requestParameters: PoizonApiControllerGetCategoryFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryFiltersResponseDto> {
        const response = await this.poizonApiControllerGetCategoryFiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Категории L1 с вложенными L3. Средний уровень groups отражает подразделы upstream: у большинства категорий группа одна, у «Одежды» их три. Ответ кэшируется на час.
     * Дерево категорий
     */
    async poizonApiControllerGetCategoryTreeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryTreeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/category-tree`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryTreeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Категории L1 с вложенными L3. Средний уровень groups отражает подразделы upstream: у большинства категорий группа одна, у «Одежды» их три. Ответ кэшируется на час.
     * Дерево категорий
     */
    async poizonApiControllerGetCategoryTree(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryTreeResponseDto> {
        const response = await this.poizonApiControllerGetCategoryTreeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Получение информации о товаре
     */
    async poizonApiControllerGetProductInfoRaw(requestParameters: PoizonApiControllerGetProductInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductInfoResponseDto>> {
        if (requestParameters['spuId'] == null) {
            throw new runtime.RequiredError(
                'spuId',
                'Required parameter "spuId" was null or undefined when calling poizonApiControllerGetProductInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/product-info/{spuId}`.replace(`{${"spuId"}}`, encodeURIComponent(String(requestParameters['spuId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductInfoResponseDtoFromJSON(jsonValue));
    }

    /**
     * Получение информации о товаре
     */
    async poizonApiControllerGetProductInfo(requestParameters: PoizonApiControllerGetProductInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductInfoResponseDto> {
        const response = await this.poizonApiControllerGetProductInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение списка отзывов о товаре
     */
    async poizonApiControllerGetReviewsRaw(requestParameters: PoizonApiControllerGetReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewListResponseDto>> {
        if (requestParameters['spuId'] == null) {
            throw new runtime.RequiredError(
                'spuId',
                'Required parameter "spuId" was null or undefined when calling poizonApiControllerGetReviews().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/reviews/{spuId}`.replace(`{${"spuId"}}`, encodeURIComponent(String(requestParameters['spuId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewListResponseDtoFromJSON(jsonValue));
    }

    /**
     * Получение списка отзывов о товаре
     */
    async poizonApiControllerGetReviews(requestParameters: PoizonApiControllerGetReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewListResponseDto> {
        const response = await this.poizonApiControllerGetReviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение размерной сетки
     */
    async poizonApiControllerGetSizeTableRaw(requestParameters: PoizonApiControllerGetSizeTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SizeTableResponseDto>> {
        if (requestParameters['spuId'] == null) {
            throw new runtime.RequiredError(
                'spuId',
                'Required parameter "spuId" was null or undefined when calling poizonApiControllerGetSizeTable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/size-table/{spuId}`.replace(`{${"spuId"}}`, encodeURIComponent(String(requestParameters['spuId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SizeTableResponseDtoFromJSON(jsonValue));
    }

    /**
     * Получение размерной сетки
     */
    async poizonApiControllerGetSizeTable(requestParameters: PoizonApiControllerGetSizeTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SizeTableResponseDto> {
        const response = await this.poizonApiControllerGetSizeTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Поиск по ключевому слову с фильтрацией по бренду, категории, серии, полу, цвету, размеру и диапазону цен. Доступные значения фильтров — в facets ответа или в GET /poizon-api/category-filters.
     * Поиск товаров
     */
    async poizonApiControllerSearchRaw(requestParameters: PoizonApiControllerSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortType'] != null) {
            queryParameters['sortType'] = requestParameters['sortType'];
        }

        if (requestParameters['sortMode'] != null) {
            queryParameters['sortMode'] = requestParameters['sortMode'];
        }

        if (requestParameters['brandIds'] != null) {
            queryParameters['brandIds'] = requestParameters['brandIds'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['categoryIds'] = requestParameters['categoryIds'];
        }

        if (requestParameters['seriesIds'] != null) {
            queryParameters['seriesIds'] = requestParameters['seriesIds'];
        }

        if (requestParameters['fitIds'] != null) {
            queryParameters['fitIds'] = requestParameters['fitIds'];
        }

        if (requestParameters['colors'] != null) {
            queryParameters['colors'] = requestParameters['colors'];
        }

        if (requestParameters['sizes'] != null) {
            queryParameters['sizes'] = requestParameters['sizes'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseDtoFromJSON(jsonValue));
    }

    /**
     * Поиск по ключевому слову с фильтрацией по бренду, категории, серии, полу, цвету, размеру и диапазону цен. Доступные значения фильтров — в facets ответа или в GET /poizon-api/category-filters.
     * Поиск товаров
     */
    async poizonApiControllerSearch(requestParameters: PoizonApiControllerSearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponseDto> {
        const response = await this.poizonApiControllerSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Поиск товаров по бренду
     */
    async poizonApiControllerSearchByBrandIdRaw(requestParameters: PoizonApiControllerSearchByBrandIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponseDto>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling poizonApiControllerSearchByBrandId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortType'] != null) {
            queryParameters['sortType'] = requestParameters['sortType'];
        }

        if (requestParameters['sortMode'] != null) {
            queryParameters['sortMode'] = requestParameters['sortMode'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['categoryIds'] = requestParameters['categoryIds'];
        }

        if (requestParameters['seriesIds'] != null) {
            queryParameters['seriesIds'] = requestParameters['seriesIds'];
        }

        if (requestParameters['fitIds'] != null) {
            queryParameters['fitIds'] = requestParameters['fitIds'];
        }

        if (requestParameters['colors'] != null) {
            queryParameters['colors'] = requestParameters['colors'];
        }

        if (requestParameters['sizes'] != null) {
            queryParameters['sizes'] = requestParameters['sizes'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['brandId'] != null) {
            queryParameters['brandId'] = requestParameters['brandId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/search-by-brand`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseDtoFromJSON(jsonValue));
    }

    /**
     * Поиск товаров по бренду
     */
    async poizonApiControllerSearchByBrandId(requestParameters: PoizonApiControllerSearchByBrandIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponseDto> {
        const response = await this.poizonApiControllerSearchByBrandIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Листинг категории любого уровня. Пагинация ограничена 1200 позициями (60 страниц по 20) — это предел upstream, поле total равно ему всегда и числом совпадений не является.
     * Поиск товаров по категории
     */
    async poizonApiControllerSearchByCategoryRaw(requestParameters: PoizonApiControllerSearchByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponseDto>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling poizonApiControllerSearchByCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortType'] != null) {
            queryParameters['sortType'] = requestParameters['sortType'];
        }

        if (requestParameters['sortMode'] != null) {
            queryParameters['sortMode'] = requestParameters['sortMode'];
        }

        if (requestParameters['brandIds'] != null) {
            queryParameters['brandIds'] = requestParameters['brandIds'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['categoryIds'] = requestParameters['categoryIds'];
        }

        if (requestParameters['seriesIds'] != null) {
            queryParameters['seriesIds'] = requestParameters['seriesIds'];
        }

        if (requestParameters['fitIds'] != null) {
            queryParameters['fitIds'] = requestParameters['fitIds'];
        }

        if (requestParameters['colors'] != null) {
            queryParameters['colors'] = requestParameters['colors'];
        }

        if (requestParameters['sizes'] != null) {
            queryParameters['sizes'] = requestParameters['sizes'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['categoryId'] = requestParameters['categoryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/poizon-api/search-by-category`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseDtoFromJSON(jsonValue));
    }

    /**
     * Листинг категории любого уровня. Пагинация ограничена 1200 позициями (60 страниц по 20) — это предел upstream, поле total равно ему всегда и числом совпадений не является.
     * Поиск товаров по категории
     */
    async poizonApiControllerSearchByCategory(requestParameters: PoizonApiControllerSearchByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponseDto> {
        const response = await this.poizonApiControllerSearchByCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const PoizonApiControllerSearchSortTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type PoizonApiControllerSearchSortTypeEnum = typeof PoizonApiControllerSearchSortTypeEnum[keyof typeof PoizonApiControllerSearchSortTypeEnum];
/**
 * @export
 */
export const PoizonApiControllerSearchSortModeEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type PoizonApiControllerSearchSortModeEnum = typeof PoizonApiControllerSearchSortModeEnum[keyof typeof PoizonApiControllerSearchSortModeEnum];
/**
 * @export
 */
export const PoizonApiControllerSearchByBrandIdSortTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type PoizonApiControllerSearchByBrandIdSortTypeEnum = typeof PoizonApiControllerSearchByBrandIdSortTypeEnum[keyof typeof PoizonApiControllerSearchByBrandIdSortTypeEnum];
/**
 * @export
 */
export const PoizonApiControllerSearchByBrandIdSortModeEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type PoizonApiControllerSearchByBrandIdSortModeEnum = typeof PoizonApiControllerSearchByBrandIdSortModeEnum[keyof typeof PoizonApiControllerSearchByBrandIdSortModeEnum];
/**
 * @export
 */
export const PoizonApiControllerSearchByCategorySortTypeEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type PoizonApiControllerSearchByCategorySortTypeEnum = typeof PoizonApiControllerSearchByCategorySortTypeEnum[keyof typeof PoizonApiControllerSearchByCategorySortTypeEnum];
/**
 * @export
 */
export const PoizonApiControllerSearchByCategorySortModeEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type PoizonApiControllerSearchByCategorySortModeEnum = typeof PoizonApiControllerSearchByCategorySortModeEnum[keyof typeof PoizonApiControllerSearchByCategorySortModeEnum];
