/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProductSelectionDto,
  ModifySelectionDto,
  ProductSelectionCountDto,
  ProductSelectionDto,
  ProductSelectionListDto,
  ProductSelectionParamKeysDto,
  ProductSelectionParamValuesDto,
  SearchProductsRequestDto,
  UpdateProductSelectionDto,
} from '../models/index';
import {
    CreateProductSelectionDtoFromJSON,
    CreateProductSelectionDtoToJSON,
    ModifySelectionDtoFromJSON,
    ModifySelectionDtoToJSON,
    ProductSelectionCountDtoFromJSON,
    ProductSelectionCountDtoToJSON,
    ProductSelectionDtoFromJSON,
    ProductSelectionDtoToJSON,
    ProductSelectionListDtoFromJSON,
    ProductSelectionListDtoToJSON,
    ProductSelectionParamKeysDtoFromJSON,
    ProductSelectionParamKeysDtoToJSON,
    ProductSelectionParamValuesDtoFromJSON,
    ProductSelectionParamValuesDtoToJSON,
    SearchProductsRequestDtoFromJSON,
    SearchProductsRequestDtoToJSON,
    UpdateProductSelectionDtoFromJSON,
    UpdateProductSelectionDtoToJSON,
} from '../models/index';

export interface ProductSelectionControllerAddProductsRequest {
    selectionId: number;
    modifySelectionDto: ModifySelectionDto;
}

export interface ProductSelectionControllerCreateRequest {
    createProductSelectionDto: CreateProductSelectionDto;
}

export interface ProductSelectionControllerDeleteSelectionRequest {
    selectionId: number;
}

export interface ProductSelectionControllerFillByFiltersRequest {
    selectionId: number;
    count: number;
    searchProductsRequestDto: SearchProductsRequestDto;
}

export interface ProductSelectionControllerGetBySelectionIdRequest {
    selectionId: number;
}

export interface ProductSelectionControllerGetParamKeysRequest {
    selectionId: number;
}

export interface ProductSelectionControllerGetParamValuesRequest {
    selectionId: number;
    key: Array<string>;
    query?: string;
    limit?: number;
    caseSensitive?: boolean;
}

export interface ProductSelectionControllerGetProductsCountRequest {
    selectionId: number;
}

export interface ProductSelectionControllerRemoveProductsRequest {
    selectionId: number;
    modifySelectionDto: ModifySelectionDto;
}

export interface ProductSelectionControllerUpdateRequest {
    selectionId: number;
    updateProductSelectionDto: UpdateProductSelectionDto;
}

/**
 * 
 */
export class ProductSelectionApi extends runtime.BaseAPI {

    /**
     * Добавить продукты в выборку
     */
    async productSelectionControllerAddProductsRaw(requestParameters: ProductSelectionControllerAddProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerAddProducts().'
            );
        }

        if (requestParameters['modifySelectionDto'] == null) {
            throw new runtime.RequiredError(
                'modifySelectionDto',
                'Required parameter "modifySelectionDto" was null or undefined when calling productSelectionControllerAddProducts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/addProducts/{selectionId}`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModifySelectionDtoToJSON(requestParameters['modifySelectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Добавить продукты в выборку
     */
    async productSelectionControllerAddProducts(requestParameters: ProductSelectionControllerAddProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerAddProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Создание выборки
     */
    async productSelectionControllerCreateRaw(requestParameters: ProductSelectionControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['createProductSelectionDto'] == null) {
            throw new runtime.RequiredError(
                'createProductSelectionDto',
                'Required parameter "createProductSelectionDto" was null or undefined when calling productSelectionControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductSelectionDtoToJSON(requestParameters['createProductSelectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Создание выборки
     */
    async productSelectionControllerCreate(requestParameters: ProductSelectionControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удалить выборку
     */
    async productSelectionControllerDeleteSelectionRaw(requestParameters: ProductSelectionControllerDeleteSelectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerDeleteSelection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Удалить выборку
     */
    async productSelectionControllerDeleteSelection(requestParameters: ProductSelectionControllerDeleteSelectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.productSelectionControllerDeleteSelectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Заполнение выборки по фильтрам поиска
     */
    async productSelectionControllerFillByFiltersRaw(requestParameters: ProductSelectionControllerFillByFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerFillByFilters().'
            );
        }

        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling productSelectionControllerFillByFilters().'
            );
        }

        if (requestParameters['searchProductsRequestDto'] == null) {
            throw new runtime.RequiredError(
                'searchProductsRequestDto',
                'Required parameter "searchProductsRequestDto" was null or undefined when calling productSelectionControllerFillByFilters().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}/fillByFilters`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchProductsRequestDtoToJSON(requestParameters['searchProductsRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Заполнение выборки по фильтрам поиска
     */
    async productSelectionControllerFillByFilters(requestParameters: ProductSelectionControllerFillByFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerFillByFiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение всех свои выборки
     */
    async productSelectionControllerGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductSelectionListDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductSelectionListDtoFromJSON));
    }

    /**
     * Получение всех свои выборки
     */
    async productSelectionControllerGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductSelectionListDto>> {
        const response = await this.productSelectionControllerGetAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Получение выборки по id
     */
    async productSelectionControllerGetBySelectionIdRaw(requestParameters: ProductSelectionControllerGetBySelectionIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerGetBySelectionId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Получение выборки по id
     */
    async productSelectionControllerGetBySelectionId(requestParameters: ProductSelectionControllerGetBySelectionIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerGetBySelectionIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Возвращает DISTINCT `Property.key` по всем товарам выборки, отсортированные по алфавиту (Postgres collation). Используется в UI маппинга для Avito-фида.
     * Уникальные ключи свойств товаров выборки
     */
    async productSelectionControllerGetParamKeysRaw(requestParameters: ProductSelectionControllerGetParamKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionParamKeysDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerGetParamKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}/paramKeys`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionParamKeysDtoFromJSON(jsonValue));
    }

    /**
     * Возвращает DISTINCT `Property.key` по всем товарам выборки, отсортированные по алфавиту (Postgres collation). Используется в UI маппинга для Avito-фида.
     * Уникальные ключи свойств товаров выборки
     */
    async productSelectionControllerGetParamKeys(requestParameters: ProductSelectionControllerGetParamKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionParamKeysDto> {
        const response = await this.productSelectionControllerGetParamKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Источник autocomplete для UI маппинга raw-значений в Avito-формате (export-api). Возвращает уникальные `Property.value` товаров выборки, у которых `Property.key` совпадает с одним из переданных query-параметров `key`. Дедупликация — first-wins по `productId ASC` (сохраняется оригинальное написание первого встретившегося значения). Сортировка — Intl.Collator(\"ru\").
     * Уникальные значения свойств товаров выборки по заданным ключам
     */
    async productSelectionControllerGetParamValuesRaw(requestParameters: ProductSelectionControllerGetParamValuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionParamValuesDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerGetParamValues().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling productSelectionControllerGetParamValues().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['caseSensitive'] != null) {
            queryParameters['caseSensitive'] = requestParameters['caseSensitive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}/paramValues`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionParamValuesDtoFromJSON(jsonValue));
    }

    /**
     * Источник autocomplete для UI маппинга raw-значений в Avito-формате (export-api). Возвращает уникальные `Property.value` товаров выборки, у которых `Property.key` совпадает с одним из переданных query-параметров `key`. Дедупликация — first-wins по `productId ASC` (сохраняется оригинальное написание первого встретившегося значения). Сортировка — Intl.Collator(\"ru\").
     * Уникальные значения свойств товаров выборки по заданным ключам
     */
    async productSelectionControllerGetParamValues(requestParameters: ProductSelectionControllerGetParamValuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionParamValuesDto> {
        const response = await this.productSelectionControllerGetParamValuesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение кол-ва товаров в выборке
     */
    async productSelectionControllerGetProductsCountRaw(requestParameters: ProductSelectionControllerGetProductsCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionCountDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerGetProductsCount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}/count`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionCountDtoFromJSON(jsonValue));
    }

    /**
     * Получение кол-ва товаров в выборке
     */
    async productSelectionControllerGetProductsCount(requestParameters: ProductSelectionControllerGetProductsCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionCountDto> {
        const response = await this.productSelectionControllerGetProductsCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Удалить продукты из выборки
     */
    async productSelectionControllerRemoveProductsRaw(requestParameters: ProductSelectionControllerRemoveProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerRemoveProducts().'
            );
        }

        if (requestParameters['modifySelectionDto'] == null) {
            throw new runtime.RequiredError(
                'modifySelectionDto',
                'Required parameter "modifySelectionDto" was null or undefined when calling productSelectionControllerRemoveProducts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/removeProducts/{selectionId}`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModifySelectionDtoToJSON(requestParameters['modifySelectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Удалить продукты из выборки
     */
    async productSelectionControllerRemoveProducts(requestParameters: ProductSelectionControllerRemoveProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerRemoveProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Обновление выборки
     */
    async productSelectionControllerUpdateRaw(requestParameters: ProductSelectionControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductSelectionDto>> {
        if (requestParameters['selectionId'] == null) {
            throw new runtime.RequiredError(
                'selectionId',
                'Required parameter "selectionId" was null or undefined when calling productSelectionControllerUpdate().'
            );
        }

        if (requestParameters['updateProductSelectionDto'] == null) {
            throw new runtime.RequiredError(
                'updateProductSelectionDto',
                'Required parameter "updateProductSelectionDto" was null or undefined when calling productSelectionControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        const response = await this.request({
            path: `/product-selection/{selectionId}`.replace(`{${"selectionId"}}`, encodeURIComponent(String(requestParameters['selectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProductSelectionDtoToJSON(requestParameters['updateProductSelectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductSelectionDtoFromJSON(jsonValue));
    }

    /**
     * Обновление выборки
     */
    async productSelectionControllerUpdate(requestParameters: ProductSelectionControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductSelectionDto> {
        const response = await this.productSelectionControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
