/* tslint:disable */
/* eslint-disable */
/**
 * Product Storage API
 * ### Poizon API Documentation  **Официальная документация Poizon API.**  #### 📚 Ресурсы  - [Официальный GitHub SDK](https://github.com/Poizon-API/public-api)  - [OpenApi JSON](https://poizon-api.com/api/product-storage/api-json)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductByExternalIdResponseDto,
  ProductDetailResponseDto,
  ProductsResponseV2WithPaginationDto,
  ProductsResponseWithPaginationDto,
  SearchProductsCountResponseDto,
} from '../models/index';
import {
    ProductByExternalIdResponseDtoFromJSON,
    ProductByExternalIdResponseDtoToJSON,
    ProductDetailResponseDtoFromJSON,
    ProductDetailResponseDtoToJSON,
    ProductsResponseV2WithPaginationDtoFromJSON,
    ProductsResponseV2WithPaginationDtoToJSON,
    ProductsResponseWithPaginationDtoFromJSON,
    ProductsResponseWithPaginationDtoToJSON,
    SearchProductsCountResponseDtoFromJSON,
    SearchProductsCountResponseDtoToJSON,
} from '../models/index';

export interface ProductControllerGetProductDetailRequest {
    id?: number;
    article?: string;
}

export interface ProductControllerGetProductDetailsByExternalIdRequest {
    externalId: string;
    source: ProductControllerGetProductDetailsByExternalIdSourceEnum;
}

export interface ProductControllerSearchRequest {
    query?: string;
    categories?: Array<number>;
    brands?: Array<number>;
    models?: Array<number>;
    genders?: Array<ProductControllerSearchGendersEnum>;
    priceMin?: number;
    priceMax?: number;
    ratingMin?: number;
    currency?: ProductControllerSearchCurrencyEnum;
    includeCustom?: boolean;
    selectionId?: number;
    excludeSelectionIds?: Array<number>;
    sources?: Array<ProductControllerSearchSourcesEnum>;
    limit?: number;
    cursor?: string;
    sortBy?: ProductControllerSearchSortByEnum;
}

export interface ProductControllerSearchCountRequest {
    query?: string;
    categories?: Array<number>;
    brands?: Array<number>;
    models?: Array<number>;
    genders?: Array<ProductControllerSearchCountGendersEnum>;
    priceMin?: number;
    priceMax?: number;
    ratingMin?: number;
    currency?: ProductControllerSearchCountCurrencyEnum;
    includeCustom?: boolean;
    selectionId?: number;
    excludeSelectionIds?: Array<number>;
    sources?: Array<ProductControllerSearchCountSourcesEnum>;
    limit?: number;
    cursor?: string;
    sortBy?: ProductControllerSearchCountSortByEnum;
}

export interface ProductControllerSearchV2Request {
    query?: string;
    categories?: Array<number>;
    brands?: Array<number>;
    models?: Array<number>;
    genders?: Array<ProductControllerSearchV2GendersEnum>;
    priceMin?: number;
    priceMax?: number;
    ratingMin?: number;
    currency?: ProductControllerSearchV2CurrencyEnum;
    includeCustom?: boolean;
    selectionId?: number;
    excludeSelectionIds?: Array<number>;
    sources?: Array<ProductControllerSearchV2SourcesEnum>;
    limit?: number;
    cursor?: string;
    sortBy?: ProductControllerSearchV2SortByEnum;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     * Получение детальной информации о продукте
     */
    async productControllerGetProductDetailRaw(requestParameters: ProductControllerGetProductDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDetailResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['article'] != null) {
            queryParameters['article'] = requestParameters['article'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/product`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDetailResponseDtoFromJSON(jsonValue));
    }

    /**
     * Получение детальной информации о продукте
     */
    async productControllerGetProductDetail(requestParameters: ProductControllerGetProductDetailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDetailResponseDto> {
        const response = await this.productControllerGetProductDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Поиск продукта по id внешнего источника
     */
    async productControllerGetProductDetailsByExternalIdRaw(requestParameters: ProductControllerGetProductDetailsByExternalIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductByExternalIdResponseDto>> {
        if (requestParameters['externalId'] == null) {
            throw new runtime.RequiredError(
                'externalId',
                'Required parameter "externalId" was null or undefined when calling productControllerGetProductDetailsByExternalId().'
            );
        }

        if (requestParameters['source'] == null) {
            throw new runtime.RequiredError(
                'source',
                'Required parameter "source" was null or undefined when calling productControllerGetProductDetailsByExternalId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['externalId'] != null) {
            queryParameters['externalId'] = requestParameters['externalId'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/product/external`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductByExternalIdResponseDtoFromJSON(jsonValue));
    }

    /**
     * Поиск продукта по id внешнего источника
     */
    async productControllerGetProductDetailsByExternalId(requestParameters: ProductControllerGetProductDetailsByExternalIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductByExternalIdResponseDto> {
        const response = await this.productControllerGetProductDetailsByExternalIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Поиск товаров по фильтрам
     */
    async productControllerSearchRaw(requestParameters: ProductControllerSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductsResponseWithPaginationDto>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['brands'] != null) {
            queryParameters['brands'] = requestParameters['brands'];
        }

        if (requestParameters['models'] != null) {
            queryParameters['models'] = requestParameters['models'];
        }

        if (requestParameters['genders'] != null) {
            queryParameters['genders'] = requestParameters['genders'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['ratingMin'] != null) {
            queryParameters['ratingMin'] = requestParameters['ratingMin'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['includeCustom'] != null) {
            queryParameters['includeCustom'] = requestParameters['includeCustom'];
        }

        if (requestParameters['selectionId'] != null) {
            queryParameters['selectionId'] = requestParameters['selectionId'];
        }

        if (requestParameters['excludeSelectionIds'] != null) {
            queryParameters['excludeSelectionIds'] = requestParameters['excludeSelectionIds'];
        }

        if (requestParameters['sources'] != null) {
            queryParameters['sources'] = requestParameters['sources'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/product/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductsResponseWithPaginationDtoFromJSON(jsonValue));
    }

    /**
     * Поиск товаров по фильтрам
     */
    async productControllerSearch(requestParameters: ProductControllerSearchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductsResponseWithPaginationDto> {
        const response = await this.productControllerSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Количество товаров по фильтрам
     */
    async productControllerSearchCountRaw(requestParameters: ProductControllerSearchCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchProductsCountResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['brands'] != null) {
            queryParameters['brands'] = requestParameters['brands'];
        }

        if (requestParameters['models'] != null) {
            queryParameters['models'] = requestParameters['models'];
        }

        if (requestParameters['genders'] != null) {
            queryParameters['genders'] = requestParameters['genders'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['ratingMin'] != null) {
            queryParameters['ratingMin'] = requestParameters['ratingMin'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['includeCustom'] != null) {
            queryParameters['includeCustom'] = requestParameters['includeCustom'];
        }

        if (requestParameters['selectionId'] != null) {
            queryParameters['selectionId'] = requestParameters['selectionId'];
        }

        if (requestParameters['excludeSelectionIds'] != null) {
            queryParameters['excludeSelectionIds'] = requestParameters['excludeSelectionIds'];
        }

        if (requestParameters['sources'] != null) {
            queryParameters['sources'] = requestParameters['sources'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/product/search/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchProductsCountResponseDtoFromJSON(jsonValue));
    }

    /**
     * Количество товаров по фильтрам
     */
    async productControllerSearchCount(requestParameters: ProductControllerSearchCountRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchProductsCountResponseDto> {
        const response = await this.productControllerSearchCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Поиск товаров по фильтрам V2
     */
    async productControllerSearchV2Raw(requestParameters: ProductControllerSearchV2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductsResponseV2WithPaginationDto>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['categories'] != null) {
            queryParameters['categories'] = requestParameters['categories'];
        }

        if (requestParameters['brands'] != null) {
            queryParameters['brands'] = requestParameters['brands'];
        }

        if (requestParameters['models'] != null) {
            queryParameters['models'] = requestParameters['models'];
        }

        if (requestParameters['genders'] != null) {
            queryParameters['genders'] = requestParameters['genders'];
        }

        if (requestParameters['priceMin'] != null) {
            queryParameters['priceMin'] = requestParameters['priceMin'];
        }

        if (requestParameters['priceMax'] != null) {
            queryParameters['priceMax'] = requestParameters['priceMax'];
        }

        if (requestParameters['ratingMin'] != null) {
            queryParameters['ratingMin'] = requestParameters['ratingMin'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['includeCustom'] != null) {
            queryParameters['includeCustom'] = requestParameters['includeCustom'];
        }

        if (requestParameters['selectionId'] != null) {
            queryParameters['selectionId'] = requestParameters['selectionId'];
        }

        if (requestParameters['excludeSelectionIds'] != null) {
            queryParameters['excludeSelectionIds'] = requestParameters['excludeSelectionIds'];
        }

        if (requestParameters['sources'] != null) {
            queryParameters['sources'] = requestParameters['sources'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // x-api-key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-service-api-key"] = await this.configuration.apiKey("x-service-api-key"); // x-service-api-key authentication
        }

        const response = await this.request({
            path: `/product/searchV2`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductsResponseV2WithPaginationDtoFromJSON(jsonValue));
    }

    /**
     * Поиск товаров по фильтрам V2
     */
    async productControllerSearchV2(requestParameters: ProductControllerSearchV2Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductsResponseV2WithPaginationDto> {
        const response = await this.productControllerSearchV2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ProductControllerGetProductDetailsByExternalIdSourceEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductControllerGetProductDetailsByExternalIdSourceEnum = typeof ProductControllerGetProductDetailsByExternalIdSourceEnum[keyof typeof ProductControllerGetProductDetailsByExternalIdSourceEnum];
/**
 * @export
 */
export const ProductControllerSearchGendersEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductControllerSearchGendersEnum = typeof ProductControllerSearchGendersEnum[keyof typeof ProductControllerSearchGendersEnum];
/**
 * @export
 */
export const ProductControllerSearchCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type ProductControllerSearchCurrencyEnum = typeof ProductControllerSearchCurrencyEnum[keyof typeof ProductControllerSearchCurrencyEnum];
/**
 * @export
 */
export const ProductControllerSearchSourcesEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductControllerSearchSourcesEnum = typeof ProductControllerSearchSourcesEnum[keyof typeof ProductControllerSearchSourcesEnum];
/**
 * @export
 */
export const ProductControllerSearchSortByEnum = {
    Relevance: 'relevance',
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Popularity: 'popularity',
    Newest: 'newest'
} as const;
export type ProductControllerSearchSortByEnum = typeof ProductControllerSearchSortByEnum[keyof typeof ProductControllerSearchSortByEnum];
/**
 * @export
 */
export const ProductControllerSearchCountGendersEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductControllerSearchCountGendersEnum = typeof ProductControllerSearchCountGendersEnum[keyof typeof ProductControllerSearchCountGendersEnum];
/**
 * @export
 */
export const ProductControllerSearchCountCurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type ProductControllerSearchCountCurrencyEnum = typeof ProductControllerSearchCountCurrencyEnum[keyof typeof ProductControllerSearchCountCurrencyEnum];
/**
 * @export
 */
export const ProductControllerSearchCountSourcesEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductControllerSearchCountSourcesEnum = typeof ProductControllerSearchCountSourcesEnum[keyof typeof ProductControllerSearchCountSourcesEnum];
/**
 * @export
 */
export const ProductControllerSearchCountSortByEnum = {
    Relevance: 'relevance',
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Popularity: 'popularity',
    Newest: 'newest'
} as const;
export type ProductControllerSearchCountSortByEnum = typeof ProductControllerSearchCountSortByEnum[keyof typeof ProductControllerSearchCountSortByEnum];
/**
 * @export
 */
export const ProductControllerSearchV2GendersEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Unisex: 'UNISEX',
    Child: 'CHILD',
    Baby: 'BABY',
    MiddleChild: 'MIDDLE_CHILD',
    EldestChild: 'ELDEST_CHILD'
} as const;
export type ProductControllerSearchV2GendersEnum = typeof ProductControllerSearchV2GendersEnum[keyof typeof ProductControllerSearchV2GendersEnum];
/**
 * @export
 */
export const ProductControllerSearchV2CurrencyEnum = {
    Rub: 'RUB',
    Cny: 'CNY',
    Eur: 'EUR',
    Usd: 'USD'
} as const;
export type ProductControllerSearchV2CurrencyEnum = typeof ProductControllerSearchV2CurrencyEnum[keyof typeof ProductControllerSearchV2CurrencyEnum];
/**
 * @export
 */
export const ProductControllerSearchV2SourcesEnum = {
    Dewu: 'DEWU',
    Poizon: 'POIZON',
    Goat: 'GOAT',
    Shihuo: 'SHIHUO'
} as const;
export type ProductControllerSearchV2SourcesEnum = typeof ProductControllerSearchV2SourcesEnum[keyof typeof ProductControllerSearchV2SourcesEnum];
/**
 * @export
 */
export const ProductControllerSearchV2SortByEnum = {
    Relevance: 'relevance',
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Popularity: 'popularity',
    Newest: 'newest'
} as const;
export type ProductControllerSearchV2SortByEnum = typeof ProductControllerSearchV2SortByEnum[keyof typeof ProductControllerSearchV2SortByEnum];
